local code = tonumber(arg[1])
local source = assert(io.open("../mutate.txt", "rb"))
local text = source:read("a")
source:close()
local total = tonumber(text:match("total mutation sites: (%d+)"))
local killed, scored = text:match("score: [%d%.]+%% %((%d+)/(%d+) killed%)")
killed, scored = tonumber(killed), tonumber(scored)
if not total or not killed or not scored or scored ~= total or (code ~= 0 and code ~= 3) then
  io.stderr:write("变异工具故障或报告不完整；详见 build/quality/mutation/mutate.txt\n")
  os.exit(1)
end
local escaped = text:gsub("\\", "\\\\"):gsub('"', '\\"'):gsub("\r", "\\r"):gsub("\n", "\\n")
local target = assert(io.open("../../mutate.json", "wb"))
target:write(string.format('{"target":"common/RateLimit.lua","total":%d,"killed":%d,"survived":%d,"tool_exit":%d,"log":"%s"}\n', total, killed, total - killed, code, escaped))
target:close()
print(string.format("变异完成：%d/%d killed，%d survived（仅报告）；build/quality/mutate.json", killed, total, total - killed))
