-- 抽奖次数与保底状态由服务端逐抽持久化；这里仅定义原奖池与已确认的价目。
return {
    Currency = '金豆',
    SinglePrice = 10,
    TenPrice = 90,
    Multiplier = 1,
    Pity = { afterMisses = 49, guaranteedDraw = 50, prizeItemKeys = { 'item108', 'item107' }, equalChance = true, resetOnJackpot = true, settleEachDraw = true, persistEachDraw = true },
    Entries = {
        { number = 1, itemName = '极品美人鱼', itemKey = 'item108', jackpot = true, weight = 10, basePrice = 1000, multiplier = 1, implemented = false, source = '地图盲盒表!R3' },
        { number = 2, itemName = '极品蛇颈龙', itemKey = 'item107', jackpot = true, weight = 10, basePrice = 900, multiplier = 1, implemented = false, source = '地图盲盒表!R4' },
        { number = 3, itemName = '极品鱼龙', itemKey = 'item106', jackpot = false, weight = 20, basePrice = 800, multiplier = 1, implemented = false, source = '地图盲盒表!R5' },
        { number = 4, itemName = '极品海绵', itemKey = 'item105', jackpot = false, weight = 20, basePrice = 700, multiplier = 1, implemented = false, source = '地图盲盒表!R6' },
        { number = 5, itemName = '极品海星', itemKey = 'item104', jackpot = false, weight = 20, basePrice = 600, multiplier = 1, implemented = false, source = '地图盲盒表!R7' },
        { number = 6, itemName = '极品章鱼', itemKey = 'item103', jackpot = false, weight = 20, basePrice = 500, multiplier = 1, implemented = false, source = '地图盲盒表!R8' },
        { number = 7, itemName = '极品信天翁', itemKey = 'item92', jackpot = false, weight = 25, basePrice = 450, multiplier = 1, implemented = false, source = '地图盲盒表!R9' },
        { number = 8, itemName = '极品军舰鸟', itemKey = 'item91', jackpot = false, weight = 25, basePrice = 400, multiplier = 1, implemented = false, source = '地图盲盒表!R10' },
        { number = 9, itemName = '极品海鸥', itemKey = 'item90', jackpot = false, weight = 25, basePrice = 350, multiplier = 1, implemented = false, source = '地图盲盒表!R11' },
        { number = 10, itemName = '极品飞鱼', itemKey = 'item89', jackpot = false, weight = 25, basePrice = 300, multiplier = 1, implemented = false, source = '地图盲盒表!R12' },
        { number = 11, itemName = '极品企鹅', itemKey = 'item88', jackpot = false, weight = 25, basePrice = 250, multiplier = 1, implemented = false, source = '地图盲盒表!R13' },
        { number = 12, itemName = '极品巨脉蜻蜓', itemKey = 'item87', jackpot = false, weight = 25, basePrice = 200, multiplier = 1, implemented = false, source = '地图盲盒表!R14' },
        { number = 13, itemName = '极品海牛', itemKey = 'item76', jackpot = false, weight = 25, basePrice = 350, multiplier = 1, implemented = false, source = '地图盲盒表!R15' },
        { number = 14, itemName = '极品海狮', itemKey = 'item75', jackpot = false, weight = 25, basePrice = 300, multiplier = 1, implemented = false, source = '地图盲盒表!R16' },
        { number = 15, itemName = '极品海狗', itemKey = 'item74', jackpot = false, weight = 25, basePrice = 250, multiplier = 1, implemented = false, source = '地图盲盒表!R17' },
        { number = 16, itemName = '极品海马', itemKey = 'item73', jackpot = false, weight = 25, basePrice = 200, multiplier = 1, implemented = false, source = '地图盲盒表!R18' },
        { number = 17, itemName = '极品海兔', itemKey = 'item72', jackpot = false, weight = 25, basePrice = 150, multiplier = 1, implemented = false, source = '地图盲盒表!R19' },
        { number = 18, itemName = '极品海参', itemKey = 'item71', jackpot = false, weight = 25, basePrice = 100, multiplier = 1, implemented = false, source = '地图盲盒表!R20' },
        { number = 19, itemName = '极品旗鱼', itemKey = 'item60', jackpot = false, weight = 25, basePrice = 80, multiplier = 1, implemented = false, source = '地图盲盒表!R21' },
        { number = 20, itemName = '极品鳐鱼', itemKey = 'item59', jackpot = false, weight = 25, basePrice = 60, multiplier = 1, implemented = false, source = '地图盲盒表!R22' },
        { number = 21, itemName = '极品翻车鲀', itemKey = 'item58', jackpot = false, weight = 25, basePrice = 50, multiplier = 1, implemented = false, source = '地图盲盒表!R23' },
        { number = 22, itemName = '极品三文鱼', itemKey = 'item57', jackpot = false, weight = 25, basePrice = 40, multiplier = 1, implemented = false, source = '地图盲盒表!R24' },
        { number = 23, itemName = '极品比目鱼', itemKey = 'item56', jackpot = false, weight = 25, basePrice = 20, multiplier = 1, implemented = false, source = '地图盲盒表!R25' },
        { number = 24, itemName = '极品海胆', itemKey = 'item55', jackpot = false, weight = 25, basePrice = 10, multiplier = 1, implemented = false, source = '地图盲盒表!R26' },
        { number = 25, itemName = '极品面包蟹', itemKey = 'item44', jackpot = false, weight = 25, basePrice = 40, multiplier = 1, implemented = false, source = '地图盲盒表!R27' },
        { number = 26, itemName = '极品青蟹', itemKey = 'item43', jackpot = false, weight = 25, basePrice = 30, multiplier = 1, implemented = false, source = '地图盲盒表!R28' },
        { number = 27, itemName = '极品梭子蟹', itemKey = 'item42', jackpot = false, weight = 25, basePrice = 25, multiplier = 1, implemented = false, source = '地图盲盒表!R29' },
        { number = 28, itemName = '极品大闸蟹', itemKey = 'item41', jackpot = false, weight = 25, basePrice = 20, multiplier = 1, implemented = false, source = '地图盲盒表!R30' },
        { number = 29, itemName = '极品寄居蟹', itemKey = 'item40', jackpot = false, weight = 25, basePrice = 10, multiplier = 1, implemented = false, source = '地图盲盒表!R31' },
        { number = 30, itemName = '极品蟛蜞', itemKey = 'item39', jackpot = false, weight = 25, basePrice = 5, multiplier = 1, implemented = false, source = '地图盲盒表!R32' },
        { number = 31, itemName = '极品奶龙', itemKey = 'rareMilkLobster', jackpot = false, weight = 25, basePrice = 21, multiplier = 1, implemented = false, source = '地图盲盒表!R33' },
        { number = 32, itemName = '极品澳龙', itemKey = 'rareAussieLobster', jackpot = false, weight = 25, basePrice = 18, multiplier = 1, implemented = false, source = '地图盲盒表!R34' },
        { number = 33, itemName = '极品波龙', itemKey = 'rareBostonLobster', jackpot = false, weight = 25, basePrice = 15, multiplier = 1, implemented = false, source = '地图盲盒表!R35' },
        { number = 34, itemName = '极品小龙虾', itemKey = 'rareCrayfish', jackpot = false, weight = 25, basePrice = 12, multiplier = 1, implemented = false, source = '地图盲盒表!R36' },
        { number = 35, itemName = '极品沼虾', itemKey = 'rareRiverShrimp', jackpot = false, weight = 25, basePrice = 10, multiplier = 1, implemented = false, source = '地图盲盒表!R37' },
        { number = 36, itemName = '极品虾米', itemKey = 'rareShrimp', jackpot = false, weight = 25, basePrice = 4, multiplier = 1, implemented = false, source = '地图盲盒表!R38' },
        { number = 37, itemName = '极品金鱼', itemKey = 'item12', jackpot = false, weight = 25, basePrice = 8, multiplier = 1, implemented = false, source = '地图盲盒表!R39' },
        { number = 38, itemName = '极品鲈鱼', itemKey = 'item11', jackpot = false, weight = 25, basePrice = 7, multiplier = 1, implemented = false, source = '地图盲盒表!R40' },
        { number = 39, itemName = '极品鲶鱼', itemKey = 'item10', jackpot = false, weight = 25, basePrice = 6, multiplier = 1, implemented = false, source = '地图盲盒表!R41' },
        { number = 40, itemName = '极品刀鱼', itemKey = 'item9', jackpot = false, weight = 25, basePrice = 5, multiplier = 1, implemented = false, source = '地图盲盒表!R42' },
        { number = 41, itemName = '极品鲤鱼', itemKey = 'item8', jackpot = false, weight = 25, basePrice = 4, multiplier = 1, implemented = false, source = '地图盲盒表!R43' },
        { number = 42, itemName = '极品罗非鱼', itemKey = 'item7', jackpot = false, weight = 25, basePrice = 3, multiplier = 1, implemented = false, source = '地图盲盒表!R44' },
    },
}
