-- #122 七区鱼种基线；source 使用原 xlsx 物理行号（含表头）。
-- SourceIdMap 的键为 编号:品级，普通与极品原编号重复但稳定字符串 ID 不重复。
-- BasePrice 取物品表；精英/首领只掉部位，自身售价为 0。Drops 对所有品级显式列出。
-- implemented=false 表示目标行为尚未完整接入；保留的旧 Model/Combat 不代表完整招式已实现。
-- SourceDescription/SourceDrops 仅保留原表内容；Q7 招式并集须由后续战斗任务落地。
return {
    Definitions = {
        -- 鱼塘
        -- #134：极品六条按鱼名复用同名普通鱼模型。原表 R11/R12 的极品鲶鱼/极品鲈鱼数值与
        -- 普通鲈鱼/鲶鱼同号行对调，数值按原表保留，模型按鱼名取（7000553 即官方「鲶鱼」）。
        tilapia = { Id = 'tilapia', SourceId = 1, Name = '罗非鱼', Grade = 'normal', ZoneId = 'fishPond', WaterId = 'fishPond.water', Health = 5, Attack = 0, Speed = 3, EscapeSec = 1, BaseWeight = 1, BasePrice = 3, Bait = 0, RodLevel = 1, DrawWeight = 8, source = '钓鱼表!R2', implemented = true, Drops = { { ItemId = 'tilapia', Count = 1 } }, Model = '7000557' },
        carp = { Id = 'carp', SourceId = 2, Name = '鲤鱼', Grade = 'normal', ZoneId = 'fishPond', WaterId = 'fishPond.water', Health = 10, Attack = 0, Speed = 3, EscapeSec = 1, BaseWeight = 5, BasePrice = 4, Bait = 'worm', RodLevel = 1, DrawWeight = 8, source = '钓鱼表!R3', implemented = true, Drops = { { ItemId = 'carp', Count = 1 } }, Model = '7000552' },
        knifeFish = { Id = 'knifeFish', SourceId = 3, Name = '刀鱼', Grade = 'normal', ZoneId = 'fishPond', WaterId = 'fishPond.water', Health = 15, Attack = 0, Speed = 3, EscapeSec = 1, BaseWeight = 0.5, BasePrice = 5, Bait = 'worm', RodLevel = 1, DrawWeight = 8, source = '钓鱼表!R4', implemented = true, Drops = { { ItemId = 'knifeFish', Count = 1 } }, SourceDescription = '刀子身，鱼尾鱼眼', Model = '7000545' },
        bass = { Id = 'bass', SourceId = 4, Name = '鲈鱼', Grade = 'normal', ZoneId = 'fishPond', WaterId = 'fishPond.water', Health = 20, Attack = 0, Speed = 3, EscapeSec = 1, BaseWeight = 2, BasePrice = 6, Bait = 'worm', RodLevel = 1, DrawWeight = 32, source = '钓鱼表!R5', implemented = true, Drops = { { ItemId = 'bass', Count = 1 } }, Model = '7000551' },
        catfish = { Id = 'catfish', SourceId = 5, Name = '鲶鱼', Grade = 'normal', ZoneId = 'fishPond', WaterId = 'fishPond.water', Health = 25, Attack = 0, Speed = 3, EscapeSec = 1, BaseWeight = 5, BasePrice = 7, Bait = 'worm', RodLevel = 1, DrawWeight = 24, source = '钓鱼表!R6', implemented = true, Drops = { { ItemId = 'catfish', Count = 1 } }, Model = '7000553' },
        goldfish = { Id = 'goldfish', SourceId = 6, Name = '金鱼', Grade = 'normal', ZoneId = 'fishPond', WaterId = 'fishPond.water', Health = 3, Attack = 0, Speed = 3, EscapeSec = 1, BaseWeight = 0.1, BasePrice = 8, Bait = 'worm', RodLevel = 1, DrawWeight = 16, source = '钓鱼表!R7', implemented = true, Drops = { { ItemId = 'goldfish', Count = 1 } }, Model = '7000559' },
        item7 = { Id = 'item7', SourceId = 1, Name = '极品罗非鱼', Grade = 'rare', ZoneId = 'fishPond', WaterId = 'fishPond.water', Health = 5, Attack = 0, Speed = 3, EscapeSec = 1, BaseWeight = 1, BasePrice = 3, Bait = 0, RodLevel = 1, DrawWeight = 2, source = '钓鱼表!R8', implemented = true, Drops = { { ItemId = 'item7', Count = 1 } }, Model = '7000557' },
        item8 = { Id = 'item8', SourceId = 2, Name = '极品鲤鱼', Grade = 'rare', ZoneId = 'fishPond', WaterId = 'fishPond.water', Health = 10, Attack = 0, Speed = 3, EscapeSec = 1, BaseWeight = 5, BasePrice = 4, Bait = 'worm', RodLevel = 1, DrawWeight = 2, source = '钓鱼表!R9', implemented = true, Drops = { { ItemId = 'item8', Count = 1 } }, Model = '7000552' },
        item9 = { Id = 'item9', SourceId = 3, Name = '极品刀鱼', Grade = 'rare', ZoneId = 'fishPond', WaterId = 'fishPond.water', Health = 15, Attack = 0, Speed = 3, EscapeSec = 1, BaseWeight = 0.5, BasePrice = 5, Bait = 'worm', RodLevel = 1, DrawWeight = 2, source = '钓鱼表!R10', implemented = true, Drops = { { ItemId = 'item9', Count = 1 } }, SourceDescription = '刀子身，鱼尾鱼眼', Model = '7000545' },
        item10 = { Id = 'item10', SourceId = 4, Name = '极品鲶鱼', Grade = 'rare', ZoneId = 'fishPond', WaterId = 'fishPond.water', Health = 20, Attack = 0, Speed = 3, EscapeSec = 1, BaseWeight = 2, BasePrice = 6, Bait = 'worm', RodLevel = 1, DrawWeight = 8, source = '钓鱼表!R11', implemented = true, Drops = { { ItemId = 'item10', Count = 1 } }, Model = '7000553' },
        item11 = { Id = 'item11', SourceId = 5, Name = '极品鲈鱼', Grade = 'rare', ZoneId = 'fishPond', WaterId = 'fishPond.water', Health = 25, Attack = 0, Speed = 3, EscapeSec = 1, BaseWeight = 5, BasePrice = 7, Bait = 'worm', RodLevel = 1, DrawWeight = 6, source = '钓鱼表!R12', implemented = true, Drops = { { ItemId = 'item11', Count = 1 } }, Model = '7000551' },
        item12 = { Id = 'item12', SourceId = 6, Name = '极品金鱼', Grade = 'rare', ZoneId = 'fishPond', WaterId = 'fishPond.water', Health = 3, Attack = 0, Speed = 3, EscapeSec = 1, BaseWeight = 0.1, BasePrice = 8, Bait = 'worm', RodLevel = 1, DrawWeight = 4, source = '钓鱼表!R13', implemented = true, Drops = { { ItemId = 'item12', Count = 1 } }, Model = '7000559' },
        eel = { Id = 'eel', SourceId = 7, Name = '电鳗', Grade = 'elite', ZoneId = 'fishPond', WaterId = 'fishPond.water', Health = 300, Attack = 10, Speed = 6, EscapeSec = 180, BaseWeight = 5, BasePrice = 0, Bait = 'worm', RodLevel = 1, DrawWeight = 10, source = '钓鱼表!R14', implemented = false, Drops = { { ItemId = 'eelMeat', Count = 2 }, { ItemId = 'eelHead', Count = 1 } }, SourceDescription = '乱甩，放电攻击周围玩家，放次技能睡10秒', Model = '7000545', Combat = 'eel' },
        alligatorGar = { Id = 'alligatorGar', SourceId = 8, Name = '鳄雀鳝', Grade = 'boss', ZoneId = 'fishPond', WaterId = 'fishPond.water', Health = 600, Attack = 30, Speed = 6, EscapeSec = 300, BaseWeight = 5, BasePrice = 0, Bait = 'duck', RodLevel = 1, DrawWeight = 100, source = '钓鱼表!R15', implemented = false, Drops = { { ItemId = 'garMeat', Count = 2 }, { ItemId = 'garHead', Count = 1 } }, SourceDescription = '鳄鱼四肢，会追着人咬，速度较慢，头有伤害，后身是弱点', Model = '7000546', Combat = 'gar' },
        -- 虾池
        shrimp = { Id = 'shrimp', SourceId = 9, Name = '虾米', Grade = 'normal', ZoneId = 'shrimpPond', WaterId = 'shrimpPond.water', Health = 20, Attack = 0, Speed = 3, EscapeSec = 1, BaseWeight = 0.02, BasePrice = 4, Bait = 0, RodLevel = 1, DrawWeight = 8, source = '钓鱼表!R16', implemented = true, Drops = { { ItemId = 'shrimp', Count = 1 } }, Model = '7000557' },
        riverShrimp = { Id = 'riverShrimp', SourceId = 10, Name = '沼虾', Grade = 'normal', ZoneId = 'shrimpPond', WaterId = 'shrimpPond.water', Health = 30, Attack = 0, Speed = 3, EscapeSec = 1, BaseWeight = 0.05, BasePrice = 10, Bait = 'sausage', RodLevel = 1, DrawWeight = 8, source = '钓鱼表!R17', implemented = true, Drops = { { ItemId = 'riverShrimp', Count = 1 } }, Model = '7000552' },
        crayfish = { Id = 'crayfish', SourceId = 11, Name = '小龙虾', Grade = 'normal', ZoneId = 'shrimpPond', WaterId = 'shrimpPond.water', Health = 40, Attack = 0, Speed = 3, EscapeSec = 1, BaseWeight = 0.1, BasePrice = 12, Bait = 'sausage', RodLevel = 1, DrawWeight = 8, source = '钓鱼表!R18', implemented = true, Drops = { { ItemId = 'crayfish', Count = 1 } }, Model = '7000545' },
        bostonLobster = { Id = 'bostonLobster', SourceId = 12, Name = '波龙', Grade = 'normal', ZoneId = 'shrimpPond', WaterId = 'shrimpPond.water', Health = 50, Attack = 0, Speed = 4, EscapeSec = 1, BaseWeight = 1, BasePrice = 15, Bait = 'sausage', RodLevel = 2, DrawWeight = 32, source = '钓鱼表!R19', implemented = true, Drops = { { ItemId = 'bostonLobster', Count = 1 } }, Model = '7000551' },
        aussieLobster = { Id = 'aussieLobster', SourceId = 13, Name = '澳龙', Grade = 'normal', ZoneId = 'shrimpPond', WaterId = 'shrimpPond.water', Health = 60, Attack = 0, Speed = 4, EscapeSec = 1, BaseWeight = 2, BasePrice = 18, Bait = 'sausage', RodLevel = 2, DrawWeight = 24, source = '钓鱼表!R20', implemented = true, Drops = { { ItemId = 'aussieLobster', Count = 1 } }, Model = '7000553' },
        milkLobster = { Id = 'milkLobster', SourceId = 14, Name = '奶龙', Grade = 'normal', ZoneId = 'shrimpPond', WaterId = 'shrimpPond.water', Health = 70, Attack = 0, Speed = 4, EscapeSec = 1, BaseWeight = 10, BasePrice = 21, Bait = 'sausage', RodLevel = 2, DrawWeight = 16, source = '钓鱼表!R21', implemented = true, Drops = { { ItemId = 'milkLobster', Count = 1 } }, Model = '7000559' },
        rareShrimp = { Id = 'rareShrimp', SourceId = 9, Name = '极品虾米', Grade = 'rare', ZoneId = 'shrimpPond', WaterId = 'shrimpPond.water', Health = 20, Attack = 0, Speed = 3, EscapeSec = 1, BaseWeight = 0.02, BasePrice = 4, Bait = 0, RodLevel = 1, DrawWeight = 2, source = '钓鱼表!R22', implemented = true, Drops = { { ItemId = 'rareShrimp', Count = 1 } }, Model = '7000557' },
        rareRiverShrimp = { Id = 'rareRiverShrimp', SourceId = 10, Name = '极品沼虾', Grade = 'rare', ZoneId = 'shrimpPond', WaterId = 'shrimpPond.water', Health = 30, Attack = 0, Speed = 3, EscapeSec = 1, BaseWeight = 0.05, BasePrice = 10, Bait = 'sausage', RodLevel = 1, DrawWeight = 2, source = '钓鱼表!R23', implemented = true, Drops = { { ItemId = 'rareRiverShrimp', Count = 1 } }, Model = '7000552' },
        rareCrayfish = { Id = 'rareCrayfish', SourceId = 11, Name = '极品小龙虾', Grade = 'rare', ZoneId = 'shrimpPond', WaterId = 'shrimpPond.water', Health = 40, Attack = 0, Speed = 3, EscapeSec = 1, BaseWeight = 0.1, BasePrice = 12, Bait = 'sausage', RodLevel = 1, DrawWeight = 2, source = '钓鱼表!R24', implemented = true, Drops = { { ItemId = 'rareCrayfish', Count = 1 } }, Model = '7000545' },
        rareBostonLobster = { Id = 'rareBostonLobster', SourceId = 12, Name = '极品波龙', Grade = 'rare', ZoneId = 'shrimpPond', WaterId = 'shrimpPond.water', Health = 50, Attack = 0, Speed = 4, EscapeSec = 1, BaseWeight = 1, BasePrice = 15, Bait = 'sausage', RodLevel = 2, DrawWeight = 8, source = '钓鱼表!R25', implemented = true, Drops = { { ItemId = 'rareBostonLobster', Count = 1 } }, Model = '7000551' },
        rareAussieLobster = { Id = 'rareAussieLobster', SourceId = 13, Name = '极品澳龙', Grade = 'rare', ZoneId = 'shrimpPond', WaterId = 'shrimpPond.water', Health = 60, Attack = 0, Speed = 4, EscapeSec = 1, BaseWeight = 2, BasePrice = 18, Bait = 'sausage', RodLevel = 2, DrawWeight = 6, source = '钓鱼表!R26', implemented = true, Drops = { { ItemId = 'rareAussieLobster', Count = 1 } }, Model = '7000553' },
        rareMilkLobster = { Id = 'rareMilkLobster', SourceId = 14, Name = '极品奶龙', Grade = 'rare', ZoneId = 'shrimpPond', WaterId = 'shrimpPond.water', Health = 70, Attack = 0, Speed = 4, EscapeSec = 1, BaseWeight = 50, BasePrice = 21, Bait = 'sausage', RodLevel = 2, DrawWeight = 4, source = '钓鱼表!R27', implemented = true, Drops = { { ItemId = 'rareMilkLobster', Count = 1 } }, Model = '7000559' },
        fish15Elite = { Id = 'fish15Elite', SourceId = 15, Name = '虾霸', Grade = 'elite', ZoneId = 'shrimpPond', WaterId = 'shrimpPond.water', Health = 600, Attack = 20, Speed = 8, EscapeSec = 180, BaseWeight = 50, BasePrice = 0, Bait = 'sausage', RodLevel = 2, DrawWeight = 10, source = '钓鱼表!R28', implemented = false, Drops = { { ItemId = 'item29', Count = 2 }, { ItemId = 'item31', Count = 1 } }, SourceDescription = '直立行走，每2秒左右开弓攻击前方玩家，打完2下尾巴戳一下将玩家戳飞，每活动15秒眩晕5秒', Model = '7000554', Combat = 'shrimp' },
        fish16Boss = { Id = 'fish16Boss', SourceId = 16, Name = '小白龙', Grade = 'boss', ZoneId = 'shrimpPond', WaterId = 'shrimpPond.water', Health = 1200, Attack = 50, Speed = 8, EscapeSec = 300, BaseWeight = 50, BasePrice = 0, Bait = 'item121', RodLevel = 1, DrawWeight = 100, source = '钓鱼表!R29', implemented = false, Drops = { { ItemId = 'item30', Count = 2 }, { ItemId = 'item32', Count = 1 } }, SourceDescription = '地上爬的一条，鹅一样啄，龙头有伤害，后身是弱点，每30秒飞起俯冲攻击玩家，落地后眩晕5秒。', Model = '7000552', Combat = 'dragon' },
        -- 蟹湖
        item33 = { Id = 'item33', SourceId = 17, Name = '蟛蜞', Grade = 'normal', ZoneId = 'crabLake', WaterId = 'crabLake.water', Health = 60, Attack = 0, Speed = 4, EscapeSec = 1, BaseWeight = 0.05, BasePrice = 5, Bait = 0, RodLevel = 1, DrawWeight = 8, source = '钓鱼表!R30', implemented = false, Drops = { { ItemId = 'item33', Count = 1 } } },
        item34 = { Id = 'item34', SourceId = 18, Name = '寄居蟹', Grade = 'normal', ZoneId = 'crabLake', WaterId = 'crabLake.water', Health = 80, Attack = 0, Speed = 4, EscapeSec = 1, BaseWeight = 0.1, BasePrice = 10, Bait = 'item115', RodLevel = 1, DrawWeight = 8, source = '钓鱼表!R31', implemented = false, Drops = { { ItemId = 'item34', Count = 1 } } },
        item35 = { Id = 'item35', SourceId = 19, Name = '大闸蟹', Grade = 'normal', ZoneId = 'crabLake', WaterId = 'crabLake.water', Health = 100, Attack = 0, Speed = 4, EscapeSec = 1, BaseWeight = 0.2, BasePrice = 20, Bait = 'item115', RodLevel = 1, DrawWeight = 8, source = '钓鱼表!R32', implemented = false, Drops = { { ItemId = 'item35', Count = 1 } } },
        item36 = { Id = 'item36', SourceId = 20, Name = '梭子蟹', Grade = 'normal', ZoneId = 'crabLake', WaterId = 'crabLake.water', Health = 120, Attack = 0, Speed = 6, EscapeSec = 1, BaseWeight = 1, BasePrice = 25, Bait = 'item115', RodLevel = 3, DrawWeight = 32, source = '钓鱼表!R33', implemented = false, Drops = { { ItemId = 'item36', Count = 1 } } },
        item37 = { Id = 'item37', SourceId = 21, Name = '青蟹', Grade = 'normal', ZoneId = 'crabLake', WaterId = 'crabLake.water', Health = 140, Attack = 0, Speed = 6, EscapeSec = 1, BaseWeight = 1.5, BasePrice = 30, Bait = 'item115', RodLevel = 3, DrawWeight = 24, source = '钓鱼表!R34', implemented = false, Drops = { { ItemId = 'item37', Count = 1 } } },
        item38 = { Id = 'item38', SourceId = 22, Name = '面包蟹', Grade = 'normal', ZoneId = 'crabLake', WaterId = 'crabLake.water', Health = 160, Attack = 0, Speed = 6, EscapeSec = 1, BaseWeight = 2, BasePrice = 40, Bait = 'item115', RodLevel = 3, DrawWeight = 16, source = '钓鱼表!R35', implemented = false, Drops = { { ItemId = 'item38', Count = 1 } } },
        item39 = { Id = 'item39', SourceId = 17, Name = '极品蟛蜞', Grade = 'rare', ZoneId = 'crabLake', WaterId = 'crabLake.water', Health = 60, Attack = 0, Speed = 4, EscapeSec = 1, BaseWeight = 0.05, BasePrice = 5, Bait = 0, RodLevel = 1, DrawWeight = 2, source = '钓鱼表!R36', implemented = false, Drops = { { ItemId = 'item39', Count = 1 } } },
        item40 = { Id = 'item40', SourceId = 18, Name = '极品寄居蟹', Grade = 'rare', ZoneId = 'crabLake', WaterId = 'crabLake.water', Health = 80, Attack = 0, Speed = 4, EscapeSec = 1, BaseWeight = 0.1, BasePrice = 10, Bait = 'item115', RodLevel = 1, DrawWeight = 2, source = '钓鱼表!R37', implemented = false, Drops = { { ItemId = 'item40', Count = 1 } } },
        item41 = { Id = 'item41', SourceId = 19, Name = '极品大闸蟹', Grade = 'rare', ZoneId = 'crabLake', WaterId = 'crabLake.water', Health = 100, Attack = 0, Speed = 4, EscapeSec = 1, BaseWeight = 0.2, BasePrice = 20, Bait = 'item115', RodLevel = 1, DrawWeight = 2, source = '钓鱼表!R38', implemented = false, Drops = { { ItemId = 'item41', Count = 1 } } },
        item42 = { Id = 'item42', SourceId = 20, Name = '极品梭子蟹', Grade = 'rare', ZoneId = 'crabLake', WaterId = 'crabLake.water', Health = 120, Attack = 0, Speed = 6, EscapeSec = 1, BaseWeight = 1, BasePrice = 25, Bait = 'item115', RodLevel = 3, DrawWeight = 8, source = '钓鱼表!R39', implemented = false, Drops = { { ItemId = 'item42', Count = 1 } } },
        item43 = { Id = 'item43', SourceId = 21, Name = '极品青蟹', Grade = 'rare', ZoneId = 'crabLake', WaterId = 'crabLake.water', Health = 140, Attack = 0, Speed = 6, EscapeSec = 1, BaseWeight = 2, BasePrice = 30, Bait = 'item115', RodLevel = 3, DrawWeight = 6, source = '钓鱼表!R40', implemented = false, Drops = { { ItemId = 'item43', Count = 1 } } },
        item44 = { Id = 'item44', SourceId = 22, Name = '极品面包蟹', Grade = 'rare', ZoneId = 'crabLake', WaterId = 'crabLake.water', Health = 160, Attack = 0, Speed = 6, EscapeSec = 1, BaseWeight = 2, BasePrice = 40, Bait = 'item115', RodLevel = 3, DrawWeight = 4, source = '钓鱼表!R41', implemented = false, Drops = { { ItemId = 'item44', Count = 1 } } },
        fish23Elite = { Id = 'fish23Elite', SourceId = 23, Name = '帝王蟹', Grade = 'elite', ZoneId = 'crabLake', WaterId = 'crabLake.water', Health = 1200, Attack = 15, Speed = 10, EscapeSec = 180, BaseWeight = 5, BasePrice = 0, Bait = 'item115', RodLevel = 3, DrawWeight = 10, source = '钓鱼表!R42', implemented = false, Drops = { { ItemId = 'item45', Count = 2 }, { ItemId = 'item47', Count = 1 } }, SourceDescription = '速度较快，每5秒对前方蟹钳乱刺，每活动30秒眩晕5秒' },
        fish24Boss = { Id = 'fish24Boss', SourceId = 24, Name = '蟹老板', Grade = 'boss', ZoneId = 'crabLake', WaterId = 'crabLake.water', Health = 2500, Attack = 20, Speed = 10, EscapeSec = 300, BaseWeight = 5, BasePrice = 0, Bait = 'item122', RodLevel = 1, DrawWeight = 100, source = '钓鱼表!R43', implemented = false, Drops = { { ItemId = 'item46', Count = 2 }, { ItemId = 'item48', Count = 1 } }, SourceDescription = '速度一般，正面用蟹钳攻击玩家每次2击，冷却时间4秒，每30秒发动冲撞，撞到有伤害' },
        -- 树林岛
        item49 = { Id = 'item49', SourceId = 25, Name = '海胆', Grade = 'normal', ZoneId = 'forestIsland', WaterId = 'forestIsland.water', Health = 140, Attack = 0, Speed = 6, EscapeSec = 1, BaseWeight = 1, BasePrice = 10, Bait = 0, RodLevel = 1, DrawWeight = 8, source = '钓鱼表!R44', implemented = false, Drops = { { ItemId = 'item49', Count = 1 } } },
        item50 = { Id = 'item50', SourceId = 26, Name = '比目鱼', Grade = 'normal', ZoneId = 'forestIsland', WaterId = 'forestIsland.water', Health = 170, Attack = 0, Speed = 6, EscapeSec = 1, BaseWeight = 2, BasePrice = 20, Bait = 'item116', RodLevel = 1, DrawWeight = 8, source = '钓鱼表!R45', implemented = false, Drops = { { ItemId = 'item50', Count = 1 } } },
        item51 = { Id = 'item51', SourceId = 27, Name = '三文鱼', Grade = 'normal', ZoneId = 'forestIsland', WaterId = 'forestIsland.water', Health = 200, Attack = 0, Speed = 6, EscapeSec = 1, BaseWeight = 3, BasePrice = 40, Bait = 'item116', RodLevel = 1, DrawWeight = 8, source = '钓鱼表!R46', implemented = false, Drops = { { ItemId = 'item51', Count = 1 } } },
        item52 = { Id = 'item52', SourceId = 28, Name = '翻车鲀', Grade = 'normal', ZoneId = 'forestIsland', WaterId = 'forestIsland.water', Health = 230, Attack = 0, Speed = 8, EscapeSec = 1, BaseWeight = 100, BasePrice = 50, Bait = 'item116', RodLevel = 4, DrawWeight = 32, source = '钓鱼表!R47', implemented = false, Drops = { { ItemId = 'item52', Count = 1 } } },
        item53 = { Id = 'item53', SourceId = 29, Name = '鳐鱼', Grade = 'normal', ZoneId = 'forestIsland', WaterId = 'forestIsland.water', Health = 260, Attack = 0, Speed = 8, EscapeSec = 1, BaseWeight = 100, BasePrice = 60, Bait = 'item116', RodLevel = 4, DrawWeight = 24, source = '钓鱼表!R48', implemented = false, Drops = { { ItemId = 'item53', Count = 1 } } },
        item54 = { Id = 'item54', SourceId = 30, Name = '旗鱼', Grade = 'normal', ZoneId = 'forestIsland', WaterId = 'forestIsland.water', Health = 290, Attack = 0, Speed = 8, EscapeSec = 1, BaseWeight = 100, BasePrice = 80, Bait = 'item116', RodLevel = 4, DrawWeight = 16, source = '钓鱼表!R49', implemented = false, Drops = { { ItemId = 'item54', Count = 1 } } },
        item55 = { Id = 'item55', SourceId = 25, Name = '极品海胆', Grade = 'rare', ZoneId = 'forestIsland', WaterId = 'forestIsland.water', Health = 140, Attack = 0, Speed = 6, EscapeSec = 1, BaseWeight = 1, BasePrice = 10, Bait = 0, RodLevel = 1, DrawWeight = 2, source = '钓鱼表!R50', implemented = false, Drops = { { ItemId = 'item55', Count = 1 } } },
        item56 = { Id = 'item56', SourceId = 26, Name = '极品比目鱼', Grade = 'rare', ZoneId = 'forestIsland', WaterId = 'forestIsland.water', Health = 170, Attack = 0, Speed = 6, EscapeSec = 1, BaseWeight = 2, BasePrice = 20, Bait = 'item116', RodLevel = 1, DrawWeight = 2, source = '钓鱼表!R51', implemented = false, Drops = { { ItemId = 'item56', Count = 1 } } },
        item57 = { Id = 'item57', SourceId = 27, Name = '极品三文鱼', Grade = 'rare', ZoneId = 'forestIsland', WaterId = 'forestIsland.water', Health = 200, Attack = 0, Speed = 6, EscapeSec = 1, BaseWeight = 3, BasePrice = 40, Bait = 'item116', RodLevel = 1, DrawWeight = 2, source = '钓鱼表!R52', implemented = false, Drops = { { ItemId = 'item57', Count = 1 } } },
        item58 = { Id = 'item58', SourceId = 28, Name = '极品翻车鲀', Grade = 'rare', ZoneId = 'forestIsland', WaterId = 'forestIsland.water', Health = 230, Attack = 0, Speed = 8, EscapeSec = 1, BaseWeight = 100, BasePrice = 50, Bait = 'item116', RodLevel = 4, DrawWeight = 8, source = '钓鱼表!R53', implemented = false, Drops = { { ItemId = 'item58', Count = 1 } } },
        item59 = { Id = 'item59', SourceId = 29, Name = '极品鳐鱼', Grade = 'rare', ZoneId = 'forestIsland', WaterId = 'forestIsland.water', Health = 260, Attack = 0, Speed = 8, EscapeSec = 1, BaseWeight = 100, BasePrice = 60, Bait = 'item116', RodLevel = 4, DrawWeight = 6, source = '钓鱼表!R54', implemented = false, Drops = { { ItemId = 'item59', Count = 1 } } },
        item60 = { Id = 'item60', SourceId = 30, Name = '极品旗鱼', Grade = 'rare', ZoneId = 'forestIsland', WaterId = 'forestIsland.water', Health = 290, Attack = 0, Speed = 8, EscapeSec = 1, BaseWeight = 100, BasePrice = 80, Bait = 'item116', RodLevel = 4, DrawWeight = 4, source = '钓鱼表!R55', implemented = false, Drops = { { ItemId = 'item60', Count = 1 } } },
        fish31Elite = { Id = 'fish31Elite', SourceId = 31, Name = '剑鱼', Grade = 'elite', ZoneId = 'forestIsland', WaterId = 'forestIsland.water', Health = 2500, Attack = 20, Speed = 12, EscapeSec = 180, BaseWeight = 100, BasePrice = 0, Bait = 'item116', RodLevel = 4, DrawWeight = 10, source = '钓鱼表!R56', implemented = false, Drops = { { ItemId = 'item61', Count = 2 }, { ItemId = 'item63', Count = 1 } }, SourceDescription = '鼻子是把剑，左右挥舞攻击，每50秒跳跃' },
        fish32Boss = { Id = 'fish32Boss', SourceId = 32, Name = '三头鲨', Grade = 'boss', ZoneId = 'forestIsland', WaterId = 'forestIsland.water', Health = 5000, Attack = 25, Speed = 12, EscapeSec = 300, BaseWeight = 100, BasePrice = 0, Bait = 'item123', RodLevel = 1, DrawWeight = 100, source = '钓鱼表!R57', implemented = false, Drops = { { ItemId = 'item62', Count = 2 }, { ItemId = 'item64', Count = 1 } }, SourceDescription = '脑袋左右横扫，范围大，冷却时间3秒。翻滚跳跃着移动，被滚到的玩家受到伤害，参照渔力全开鲨鱼', SourceDrops = '鱼翅×2,三连鲨鱼头×1', DecisionSource = '策划案已确认结论.md#Q10' },
        -- 沙滩岛
        item65 = { Id = 'item65', SourceId = 33, Name = '海参', Grade = 'normal', ZoneId = 'beachIsland', WaterId = 'beachIsland.water', Health = 260, Attack = 0, Speed = 7, EscapeSec = 1, BaseWeight = 1, BasePrice = 100, Bait = 0, RodLevel = 1, DrawWeight = 8, source = '钓鱼表!R58', implemented = false, Drops = { { ItemId = 'item65', Count = 1 } }, SourceDescription = '人参' },
        item66 = { Id = 'item66', SourceId = 34, Name = '海兔', Grade = 'normal', ZoneId = 'beachIsland', WaterId = 'beachIsland.water', Health = 300, Attack = 0, Speed = 7, EscapeSec = 1, BaseWeight = 1, BasePrice = 150, Bait = 'item117', RodLevel = 1, DrawWeight = 8, source = '钓鱼表!R59', implemented = false, Drops = { { ItemId = 'item66', Count = 1 } }, SourceDescription = '兔子' },
        item67 = { Id = 'item67', SourceId = 35, Name = '海马', Grade = 'normal', ZoneId = 'beachIsland', WaterId = 'beachIsland.water', Health = 340, Attack = 0, Speed = 7, EscapeSec = 1, BaseWeight = 5, BasePrice = 200, Bait = 'item117', RodLevel = 1, DrawWeight = 8, source = '钓鱼表!R60', implemented = false, Drops = { { ItemId = 'item67', Count = 1 } }, SourceDescription = '马' },
        item68 = { Id = 'item68', SourceId = 36, Name = '海狗', Grade = 'normal', ZoneId = 'beachIsland', WaterId = 'beachIsland.water', Health = 380, Attack = 0, Speed = 9, EscapeSec = 1, BaseWeight = 50, BasePrice = 250, Bait = 'item117', RodLevel = 5, DrawWeight = 32, source = '钓鱼表!R61', implemented = false, Drops = { { ItemId = 'item68', Count = 1 } }, SourceDescription = '狗头鱼身' },
        item69 = { Id = 'item69', SourceId = 37, Name = '海狮', Grade = 'normal', ZoneId = 'beachIsland', WaterId = 'beachIsland.water', Health = 420, Attack = 0, Speed = 9, EscapeSec = 1, BaseWeight = 200, BasePrice = 300, Bait = 'item117', RodLevel = 5, DrawWeight = 24, source = '钓鱼表!R62', implemented = false, Drops = { { ItemId = 'item69', Count = 1 } }, SourceDescription = '狮子头鱼身' },
        item70 = { Id = 'item70', SourceId = 38, Name = '海牛', Grade = 'normal', ZoneId = 'beachIsland', WaterId = 'beachIsland.water', Health = 460, Attack = 0, Speed = 9, EscapeSec = 1, BaseWeight = 500, BasePrice = 350, Bait = 'item117', RodLevel = 5, DrawWeight = 16, source = '钓鱼表!R63', implemented = false, Drops = { { ItemId = 'item70', Count = 1 } }, SourceDescription = '牛头鱼身' },
        item71 = { Id = 'item71', SourceId = 33, Name = '极品海参', Grade = 'rare', ZoneId = 'beachIsland', WaterId = 'beachIsland.water', Health = 260, Attack = 0, Speed = 7, EscapeSec = 1, BaseWeight = 1, BasePrice = 100, Bait = 0, RodLevel = 1, DrawWeight = 2, source = '钓鱼表!R64', implemented = false, Drops = { { ItemId = 'item71', Count = 1 } }, SourceDescription = '人参' },
        item72 = { Id = 'item72', SourceId = 34, Name = '极品海兔', Grade = 'rare', ZoneId = 'beachIsland', WaterId = 'beachIsland.water', Health = 300, Attack = 0, Speed = 7, EscapeSec = 1, BaseWeight = 1, BasePrice = 150, Bait = 'item117', RodLevel = 1, DrawWeight = 2, source = '钓鱼表!R65', implemented = false, Drops = { { ItemId = 'item72', Count = 1 } }, SourceDescription = '兔子' },
        item73 = { Id = 'item73', SourceId = 35, Name = '极品海马', Grade = 'rare', ZoneId = 'beachIsland', WaterId = 'beachIsland.water', Health = 340, Attack = 0, Speed = 7, EscapeSec = 1, BaseWeight = 5, BasePrice = 200, Bait = 'item117', RodLevel = 1, DrawWeight = 2, source = '钓鱼表!R66', implemented = false, Drops = { { ItemId = 'item73', Count = 1 } }, SourceDescription = '马' },
        item74 = { Id = 'item74', SourceId = 36, Name = '极品海狗', Grade = 'rare', ZoneId = 'beachIsland', WaterId = 'beachIsland.water', Health = 380, Attack = 0, Speed = 9, EscapeSec = 1, BaseWeight = 50, BasePrice = 250, Bait = 'item117', RodLevel = 5, DrawWeight = 8, source = '钓鱼表!R67', implemented = false, Drops = { { ItemId = 'item74', Count = 1 } }, SourceDescription = '狗头鱼身' },
        item75 = { Id = 'item75', SourceId = 37, Name = '极品海狮', Grade = 'rare', ZoneId = 'beachIsland', WaterId = 'beachIsland.water', Health = 420, Attack = 0, Speed = 9, EscapeSec = 1, BaseWeight = 200, BasePrice = 300, Bait = 'item117', RodLevel = 5, DrawWeight = 6, source = '钓鱼表!R68', implemented = false, Drops = { { ItemId = 'item75', Count = 1 } }, SourceDescription = '狮子头鱼身' },
        item76 = { Id = 'item76', SourceId = 38, Name = '极品海牛', Grade = 'rare', ZoneId = 'beachIsland', WaterId = 'beachIsland.water', Health = 460, Attack = 0, Speed = 9, EscapeSec = 1, BaseWeight = 500, BasePrice = 350, Bait = 'item117', RodLevel = 5, DrawWeight = 4, source = '钓鱼表!R69', implemented = false, Drops = { { ItemId = 'item76', Count = 1 } }, SourceDescription = '牛头鱼身' },
        fish39Elite = { Id = 'fish39Elite', SourceId = 39, Name = '海象', Grade = 'elite', ZoneId = 'beachIsland', WaterId = 'beachIsland.water', Health = 3000, Attack = 25, Speed = 11, EscapeSec = 180, BaseWeight = 2000, BasePrice = 0, Bait = 'item117', RodLevel = 5, DrawWeight = 10, source = '钓鱼表!R70', implemented = false, Drops = { { ItemId = 'item77', Count = 2 }, { ItemId = 'item79', Count = 1 } }, SourceDescription = '象头鱼身，甩头用象牙乱刺，每40秒发动一次蛄蛹突击' },
        fish40Boss = { Id = 'fish40Boss', SourceId = 40, Name = '虎鲸', Grade = 'boss', ZoneId = 'beachIsland', WaterId = 'beachIsland.water', Health = 6000, Attack = 30, Speed = 13, EscapeSec = 300, BaseWeight = 3000, BasePrice = 0, Bait = 'item124', RodLevel = 1, DrawWeight = 100, source = '钓鱼表!R71', implemented = false, Drops = { { ItemId = 'item78', Count = 2 }, { ItemId = 'item80', Count = 1 } }, SourceDescription = '虎头虎爪鲸尾，每2秒对进身单位发动爪击，每10秒发动虎啸打出虎头炮远程攻击，每25秒鲸跃砸击远距离玩家。' },
        -- 礁石岛
        item81 = { Id = 'item81', SourceId = 41, Name = '巨脉蜻蜓', Grade = 'normal', ZoneId = 'reefIsland', WaterId = 'reefIsland.water', Health = 400, Attack = 0, Speed = 8, EscapeSec = 1, BaseWeight = 0.5, BasePrice = 200, Bait = 0, RodLevel = 1, DrawWeight = 8, source = '钓鱼表!R72', implemented = false, Drops = { { ItemId = 'item81', Count = 1 } } },
        item82 = { Id = 'item82', SourceId = 42, Name = '企鹅', Grade = 'normal', ZoneId = 'reefIsland', WaterId = 'reefIsland.water', Health = 450, Attack = 0, Speed = 8, EscapeSec = 1, BaseWeight = 5, BasePrice = 250, Bait = 'item118', RodLevel = 1, DrawWeight = 8, source = '钓鱼表!R73', implemented = false, Drops = { { ItemId = 'item82', Count = 1 } }, SourceDescription = '红围巾' },
        item83 = { Id = 'item83', SourceId = 43, Name = '飞鱼', Grade = 'normal', ZoneId = 'reefIsland', WaterId = 'reefIsland.water', Health = 500, Attack = 0, Speed = 8, EscapeSec = 1, BaseWeight = 1, BasePrice = 300, Bait = 'item118', RodLevel = 1, DrawWeight = 8, source = '钓鱼表!R74', implemented = false, Drops = { { ItemId = 'item83', Count = 1 } } },
        item84 = { Id = 'item84', SourceId = 44, Name = '海鸥', Grade = 'normal', ZoneId = 'reefIsland', WaterId = 'reefIsland.water', Health = 550, Attack = 0, Speed = 10, EscapeSec = 1, BaseWeight = 2.5, BasePrice = 350, Bait = 'item118', RodLevel = 6, DrawWeight = 32, source = '钓鱼表!R75', implemented = false, Drops = { { ItemId = 'item84', Count = 1 } } },
        item85 = { Id = 'item85', SourceId = 45, Name = '军舰鸟', Grade = 'normal', ZoneId = 'reefIsland', WaterId = 'reefIsland.water', Health = 600, Attack = 0, Speed = 10, EscapeSec = 1, BaseWeight = 15, BasePrice = 400, Bait = 'item118', RodLevel = 6, DrawWeight = 24, source = '钓鱼表!R76', implemented = false, Drops = { { ItemId = 'item85', Count = 1 } } },
        item86 = { Id = 'item86', SourceId = 46, Name = '信天翁', Grade = 'normal', ZoneId = 'reefIsland', WaterId = 'reefIsland.water', Health = 650, Attack = 0, Speed = 10, EscapeSec = 1, BaseWeight = 30, BasePrice = 450, Bait = 'item118', RodLevel = 6, DrawWeight = 16, source = '钓鱼表!R77', implemented = false, Drops = { { ItemId = 'item86', Count = 1 } } },
        item87 = { Id = 'item87', SourceId = 41, Name = '极品巨脉蜻蜓', Grade = 'rare', ZoneId = 'reefIsland', WaterId = 'reefIsland.water', Health = 400, Attack = 0, Speed = 8, EscapeSec = 1, BaseWeight = 0.5, BasePrice = 200, Bait = 0, RodLevel = 1, DrawWeight = 2, source = '钓鱼表!R78', implemented = false, Drops = { { ItemId = 'item87', Count = 1 } } },
        item88 = { Id = 'item88', SourceId = 42, Name = '极品企鹅', Grade = 'rare', ZoneId = 'reefIsland', WaterId = 'reefIsland.water', Health = 450, Attack = 0, Speed = 8, EscapeSec = 1, BaseWeight = 5, BasePrice = 250, Bait = 'item118', RodLevel = 1, DrawWeight = 2, source = '钓鱼表!R79', implemented = false, Drops = { { ItemId = 'item88', Count = 1 } }, SourceDescription = '红围巾' },
        item89 = { Id = 'item89', SourceId = 43, Name = '极品飞鱼', Grade = 'rare', ZoneId = 'reefIsland', WaterId = 'reefIsland.water', Health = 500, Attack = 0, Speed = 8, EscapeSec = 1, BaseWeight = 1, BasePrice = 300, Bait = 'item118', RodLevel = 1, DrawWeight = 2, source = '钓鱼表!R80', implemented = false, Drops = { { ItemId = 'item89', Count = 1 } } },
        item90 = { Id = 'item90', SourceId = 44, Name = '极品海鸥', Grade = 'rare', ZoneId = 'reefIsland', WaterId = 'reefIsland.water', Health = 550, Attack = 0, Speed = 10, EscapeSec = 1, BaseWeight = 2.5, BasePrice = 350, Bait = 'item118', RodLevel = 6, DrawWeight = 8, source = '钓鱼表!R81', implemented = false, Drops = { { ItemId = 'item90', Count = 1 } } },
        item91 = { Id = 'item91', SourceId = 45, Name = '极品军舰鸟', Grade = 'rare', ZoneId = 'reefIsland', WaterId = 'reefIsland.water', Health = 600, Attack = 0, Speed = 10, EscapeSec = 1, BaseWeight = 15, BasePrice = 400, Bait = 'item118', RodLevel = 6, DrawWeight = 6, source = '钓鱼表!R82', implemented = false, Drops = { { ItemId = 'item91', Count = 1 } } },
        item92 = { Id = 'item92', SourceId = 46, Name = '极品信天翁', Grade = 'rare', ZoneId = 'reefIsland', WaterId = 'reefIsland.water', Health = 650, Attack = 0, Speed = 10, EscapeSec = 1, BaseWeight = 30, BasePrice = 450, Bait = 'item118', RodLevel = 6, DrawWeight = 4, source = '钓鱼表!R83', implemented = false, Drops = { { ItemId = 'item92', Count = 1 } } },
        fish47Elite = { Id = 'fish47Elite', SourceId = 47, Name = '白头鹰', Grade = 'elite', ZoneId = 'reefIsland', WaterId = 'reefIsland.water', Health = 6000, Attack = 30, Speed = 20, EscapeSec = 180, BaseWeight = 30, BasePrice = 0, Bait = 'item118', RodLevel = 6, DrawWeight = 10, source = '钓鱼表!R84', implemented = false, Drops = { { ItemId = 'item93', Count = 2 }, { ItemId = 'item95', Count = 1 } }, SourceDescription = '每20秒一次俯冲攻击', SourceDrops = '翅膀×2,鹰头×1', DecisionSource = '策划案已确认结论.md#Q10' },
        fish48Boss = { Id = 'fish48Boss', SourceId = 48, Name = '风神翼龙', Grade = 'boss', ZoneId = 'reefIsland', WaterId = 'reefIsland.water', Health = 12000, Attack = 35, Speed = 20, EscapeSec = 300, BaseWeight = 100, BasePrice = 0, Bait = 'item125', RodLevel = 1, DrawWeight = 100, source = '钓鱼表!R85', implemented = false, Drops = { { ItemId = 'item94', Count = 2 }, { ItemId = 'item96', Count = 1 } }, SourceDescription = '每20秒一次俯冲攻击，每4秒投掷一发龙屎' },
        -- 火山岛
        item97 = { Id = 'item97', SourceId = 49, Name = '章鱼', Grade = 'normal', ZoneId = 'volcanoIsland', WaterId = 'volcanoIsland.water', Health = 500, Attack = 0, Speed = 9, EscapeSec = 1, BaseWeight = 2, BasePrice = 500, Bait = 0, RodLevel = 1, DrawWeight = 8, source = '钓鱼表!R86', implemented = false, Drops = { { ItemId = 'item97', Count = 1 } }, SourceDescription = '章鱼哥' },
        item98 = { Id = 'item98', SourceId = 50, Name = '海星', Grade = 'normal', ZoneId = 'volcanoIsland', WaterId = 'volcanoIsland.water', Health = 600, Attack = 0, Speed = 9, EscapeSec = 1, BaseWeight = 5, BasePrice = 600, Bait = 'item119', RodLevel = 1, DrawWeight = 8, source = '钓鱼表!R87', implemented = false, Drops = { { ItemId = 'item98', Count = 1 } }, SourceDescription = '派大星' },
        item99 = { Id = 'item99', SourceId = 51, Name = '海绵', Grade = 'normal', ZoneId = 'volcanoIsland', WaterId = 'volcanoIsland.water', Health = 700, Attack = 0, Speed = 9, EscapeSec = 1, BaseWeight = 1, BasePrice = 700, Bait = 'item119', RodLevel = 1, DrawWeight = 8, source = '钓鱼表!R88', implemented = false, Drops = { { ItemId = 'item99', Count = 1 } }, SourceDescription = '海绵宝宝' },
        item100 = { Id = 'item100', SourceId = 52, Name = '鱼龙', Grade = 'normal', ZoneId = 'volcanoIsland', WaterId = 'volcanoIsland.water', Health = 800, Attack = 0, Speed = 11, EscapeSec = 1, BaseWeight = 10000, BasePrice = 800, Bait = 'item119', RodLevel = 7, DrawWeight = 32, source = '钓鱼表!R89', implemented = false, Drops = { { ItemId = 'item100', Count = 1 } } },
        item101 = { Id = 'item101', SourceId = 53, Name = '蛇颈龙', Grade = 'normal', ZoneId = 'volcanoIsland', WaterId = 'volcanoIsland.water', Health = 900, Attack = 0, Speed = 11, EscapeSec = 1, BaseWeight = 15000, BasePrice = 900, Bait = 'item119', RodLevel = 7, DrawWeight = 24, source = '钓鱼表!R90', implemented = false, Drops = { { ItemId = 'item101', Count = 1 } } },
        item102 = { Id = 'item102', SourceId = 54, Name = '美人鱼', Grade = 'normal', ZoneId = 'volcanoIsland', WaterId = 'volcanoIsland.water', Health = 1000, Attack = 0, Speed = 11, EscapeSec = 1, BaseWeight = 40, BasePrice = 1000, Bait = 'item119', RodLevel = 7, DrawWeight = 16, source = '钓鱼表!R91', implemented = false, Drops = { { ItemId = 'item102', Count = 1 } } },
        item103 = { Id = 'item103', SourceId = 49, Name = '极品章鱼', Grade = 'rare', ZoneId = 'volcanoIsland', WaterId = 'volcanoIsland.water', Health = 500, Attack = 0, Speed = 9, EscapeSec = 1, BaseWeight = 2, BasePrice = 500, Bait = 0, RodLevel = 1, DrawWeight = 2, source = '钓鱼表!R92', implemented = false, Drops = { { ItemId = 'item103', Count = 1 } }, SourceDescription = '章鱼哥' },
        item104 = { Id = 'item104', SourceId = 50, Name = '极品海星', Grade = 'rare', ZoneId = 'volcanoIsland', WaterId = 'volcanoIsland.water', Health = 600, Attack = 0, Speed = 9, EscapeSec = 1, BaseWeight = 5, BasePrice = 600, Bait = 'item119', RodLevel = 1, DrawWeight = 2, source = '钓鱼表!R93', implemented = false, Drops = { { ItemId = 'item104', Count = 1 } }, SourceDescription = '派大星' },
        item105 = { Id = 'item105', SourceId = 51, Name = '极品海绵', Grade = 'rare', ZoneId = 'volcanoIsland', WaterId = 'volcanoIsland.water', Health = 700, Attack = 0, Speed = 9, EscapeSec = 1, BaseWeight = 1, BasePrice = 700, Bait = 'item119', RodLevel = 1, DrawWeight = 2, source = '钓鱼表!R94', implemented = false, Drops = { { ItemId = 'item105', Count = 1 } }, SourceDescription = '海绵宝宝' },
        item106 = { Id = 'item106', SourceId = 52, Name = '极品鱼龙', Grade = 'rare', ZoneId = 'volcanoIsland', WaterId = 'volcanoIsland.water', Health = 800, Attack = 0, Speed = 11, EscapeSec = 1, BaseWeight = 10000, BasePrice = 800, Bait = 'item119', RodLevel = 7, DrawWeight = 8, source = '钓鱼表!R95', implemented = false, Drops = { { ItemId = 'item106', Count = 1 } } },
        item107 = { Id = 'item107', SourceId = 53, Name = '极品蛇颈龙', Grade = 'rare', ZoneId = 'volcanoIsland', WaterId = 'volcanoIsland.water', Health = 900, Attack = 0, Speed = 11, EscapeSec = 1, BaseWeight = 10000, BasePrice = 900, Bait = 'item119', RodLevel = 7, DrawWeight = 6, source = '钓鱼表!R96', implemented = false, Drops = { { ItemId = 'item107', Count = 1 } } },
        item108 = { Id = 'item108', SourceId = 54, Name = '极品美人鱼', Grade = 'rare', ZoneId = 'volcanoIsland', WaterId = 'volcanoIsland.water', Health = 1000, Attack = 0, Speed = 11, EscapeSec = 1, BaseWeight = 40, BasePrice = 1000, Bait = 'item119', RodLevel = 7, DrawWeight = 4, source = '钓鱼表!R97', implemented = false, Drops = { { ItemId = 'item108', Count = 1 } } },
        fish55Elite = { Id = 'fish55Elite', SourceId = 55, Name = '沧龙', Grade = 'elite', ZoneId = 'volcanoIsland', WaterId = 'volcanoIsland.water', Health = 12000, Attack = 35, Speed = 13, EscapeSec = 180, BaseWeight = 20000, BasePrice = 0, Bait = 'item119', RodLevel = 7, DrawWeight = 10, source = '钓鱼表!R98', implemented = false, Drops = { { ItemId = 'item109', Count = 2 }, { ItemId = 'item111', Count = 1 } }, SourceDescription = '每15秒高高跃起，砸击玩家，落地后甩头攻击周围玩家。' },
        fish56Boss = { Id = 'fish56Boss', SourceId = 56, Name = '哥斯拉', Grade = 'boss', ZoneId = 'volcanoIsland', WaterId = 'volcanoIsland.water', Health = 25000, Attack = 50, Speed = 15, EscapeSec = 300, BaseWeight = 50000000, BasePrice = 0, Bait = 'item126', RodLevel = 1, DrawWeight = 100, source = '钓鱼表!R99', implemented = false, Drops = { { ItemId = 'item110', Count = 2 }, { ItemId = 'item112', Count = 1 } }, SourceDescription = '普攻2秒爪击，每6秒一次甩尾，每30秒一次原子吐息，一线攻击前方10米范围，被击中秒杀。' },
    },
    SourceIdMap = {
        ['1:normal'] = 'tilapia',
        ['2:normal'] = 'carp',
        ['3:normal'] = 'knifeFish',
        ['4:normal'] = 'bass',
        ['5:normal'] = 'catfish',
        ['6:normal'] = 'goldfish',
        ['1:rare'] = 'item7',
        ['2:rare'] = 'item8',
        ['3:rare'] = 'item9',
        ['4:rare'] = 'item10',
        ['5:rare'] = 'item11',
        ['6:rare'] = 'item12',
        ['7:elite'] = 'eel',
        ['8:boss'] = 'alligatorGar',
        ['9:normal'] = 'shrimp',
        ['10:normal'] = 'riverShrimp',
        ['11:normal'] = 'crayfish',
        ['12:normal'] = 'bostonLobster',
        ['13:normal'] = 'aussieLobster',
        ['14:normal'] = 'milkLobster',
        ['9:rare'] = 'rareShrimp',
        ['10:rare'] = 'rareRiverShrimp',
        ['11:rare'] = 'rareCrayfish',
        ['12:rare'] = 'rareBostonLobster',
        ['13:rare'] = 'rareAussieLobster',
        ['14:rare'] = 'rareMilkLobster',
        ['15:elite'] = 'fish15Elite',
        ['16:boss'] = 'fish16Boss',
        ['17:normal'] = 'item33',
        ['18:normal'] = 'item34',
        ['19:normal'] = 'item35',
        ['20:normal'] = 'item36',
        ['21:normal'] = 'item37',
        ['22:normal'] = 'item38',
        ['17:rare'] = 'item39',
        ['18:rare'] = 'item40',
        ['19:rare'] = 'item41',
        ['20:rare'] = 'item42',
        ['21:rare'] = 'item43',
        ['22:rare'] = 'item44',
        ['23:elite'] = 'fish23Elite',
        ['24:boss'] = 'fish24Boss',
        ['25:normal'] = 'item49',
        ['26:normal'] = 'item50',
        ['27:normal'] = 'item51',
        ['28:normal'] = 'item52',
        ['29:normal'] = 'item53',
        ['30:normal'] = 'item54',
        ['25:rare'] = 'item55',
        ['26:rare'] = 'item56',
        ['27:rare'] = 'item57',
        ['28:rare'] = 'item58',
        ['29:rare'] = 'item59',
        ['30:rare'] = 'item60',
        ['31:elite'] = 'fish31Elite',
        ['32:boss'] = 'fish32Boss',
        ['33:normal'] = 'item65',
        ['34:normal'] = 'item66',
        ['35:normal'] = 'item67',
        ['36:normal'] = 'item68',
        ['37:normal'] = 'item69',
        ['38:normal'] = 'item70',
        ['33:rare'] = 'item71',
        ['34:rare'] = 'item72',
        ['35:rare'] = 'item73',
        ['36:rare'] = 'item74',
        ['37:rare'] = 'item75',
        ['38:rare'] = 'item76',
        ['39:elite'] = 'fish39Elite',
        ['40:boss'] = 'fish40Boss',
        ['41:normal'] = 'item81',
        ['42:normal'] = 'item82',
        ['43:normal'] = 'item83',
        ['44:normal'] = 'item84',
        ['45:normal'] = 'item85',
        ['46:normal'] = 'item86',
        ['41:rare'] = 'item87',
        ['42:rare'] = 'item88',
        ['43:rare'] = 'item89',
        ['44:rare'] = 'item90',
        ['45:rare'] = 'item91',
        ['46:rare'] = 'item92',
        ['47:elite'] = 'fish47Elite',
        ['48:boss'] = 'fish48Boss',
        ['49:normal'] = 'item97',
        ['50:normal'] = 'item98',
        ['51:normal'] = 'item99',
        ['52:normal'] = 'item100',
        ['53:normal'] = 'item101',
        ['54:normal'] = 'item102',
        ['49:rare'] = 'item103',
        ['50:rare'] = 'item104',
        ['51:rare'] = 'item105',
        ['52:rare'] = 'item106',
        ['53:rare'] = 'item107',
        ['54:rare'] = 'item108',
        ['55:elite'] = 'fish55Elite',
        ['56:boss'] = 'fish56Boss',
    },
    LegacyIdMap = {
        tilapia = 'tilapia',
        carp = 'carp',
        knifeFish = 'knifeFish',
        bass = 'bass',
        catfish = 'catfish',
        goldfish = 'goldfish',
        eel = 'eel',
        alligatorGar = 'alligatorGar',
        shrimp = 'shrimp',
        riverShrimp = 'riverShrimp',
        crayfish = 'crayfish',
        bostonLobster = 'bostonLobster',
        aussieLobster = 'aussieLobster',
        milkLobster = 'milkLobster',
        rareShrimp = 'rareShrimp',
        rareRiverShrimp = 'rareRiverShrimp',
        rareCrayfish = 'rareCrayfish',
        rareBostonLobster = 'rareBostonLobster',
        rareAussieLobster = 'rareAussieLobster',
        rareMilkLobster = 'rareMilkLobster',
    },
}
