-- #122 物品全量基线。source 使用原 xlsx 物理行号（含表头）；BasePrice 仅为回收价。
-- 旧 ID 保留，新 ID 固定为 item + 物品表编号；SourceIdMap 供商店、奖池等按源表关联。
-- implemented 只表示现有基础使用链已接入；新增行为及特殊道具仍由后续任务实现。
-- SourceDescription 保留原表备注，不作为已实现效果；无图标的新物品不编造资产引用。
return {
    Definitions = {
        -- 鱼塘鱼获
        tilapia = { Id = 'tilapia', SourceId = 1, Name = '罗非鱼', Type = '食物', BasePrice = 3, source = '物品表!R2', implemented = true, EatPercent = 15, Icon = 'official://image/11164' },
        carp = { Id = 'carp', SourceId = 2, Name = '鲤鱼', Type = '食物', BasePrice = 4, source = '物品表!R3', implemented = true, EatPercent = 20, Icon = 'official://image/11164' },
        knifeFish = { Id = 'knifeFish', SourceId = 3, Name = '刀鱼', Type = '食物', BasePrice = 5, source = '物品表!R4', implemented = true, EatPercent = 20, Icon = 'official://image/11164' },
        bass = { Id = 'bass', SourceId = 4, Name = '鲈鱼', Type = '食物', BasePrice = 6, source = '物品表!R5', implemented = true, EatPercent = 25, Icon = 'official://image/11164' },
        catfish = { Id = 'catfish', SourceId = 5, Name = '鲶鱼', Type = '食物', BasePrice = 7, source = '物品表!R6', implemented = true, EatPercent = 25, Icon = 'official://image/11164' },
        goldfish = { Id = 'goldfish', SourceId = 6, Name = '金鱼', Type = '食物', BasePrice = 8, source = '物品表!R7', implemented = true, EatPercent = 30, Icon = 'official://image/11164' },
        item7 = { Id = 'item7', SourceId = 7, Name = '极品罗非鱼', Type = '极品食物', BasePrice = 3, source = '物品表!R8', implemented = false, EatPercent = 15 },
        item8 = { Id = 'item8', SourceId = 8, Name = '极品鲤鱼', Type = '极品食物', BasePrice = 4, source = '物品表!R9', implemented = false, EatPercent = 20 },
        item9 = { Id = 'item9', SourceId = 9, Name = '极品刀鱼', Type = '极品食物', BasePrice = 5, source = '物品表!R10', implemented = false, EatPercent = 20 },
        item10 = { Id = 'item10', SourceId = 10, Name = '极品鲶鱼', Type = '极品食物', BasePrice = 6, source = '物品表!R11', implemented = false, EatPercent = 25 },
        item11 = { Id = 'item11', SourceId = 11, Name = '极品鲈鱼', Type = '极品食物', BasePrice = 7, source = '物品表!R12', implemented = false, EatPercent = 25 },
        item12 = { Id = 'item12', SourceId = 12, Name = '极品金鱼', Type = '极品食物', BasePrice = 8, source = '物品表!R13', implemented = false, EatPercent = 30 },
        eelMeat = { Id = 'eelMeat', SourceId = 13, Name = '电鳗肉', Type = '食物', BasePrice = 10, source = '物品表!R14', implemented = true, EatPercent = 50, Icon = 'official://image/13008' },
        garMeat = { Id = 'garMeat', SourceId = 14, Name = '鳄雀鳝鱼肉', Type = '食物', BasePrice = 15, source = '物品表!R15', implemented = true, EatPercent = 100, Icon = 'official://image/13008' },
        eelHead = { Id = 'eelHead', SourceId = 15, Name = '电鳗头', Type = '极品食物', BasePrice = 10, source = '物品表!R16', implemented = true, EatPercent = 50, Icon = 'official://image/11164' },
        garHead = { Id = 'garHead', SourceId = 16, Name = '鳄雀鳝鱼头', Type = '极品食物', BasePrice = 20, source = '物品表!R17', implemented = true, EatPercent = 100, Icon = 'official://image/11164' },
        -- 虾池鱼获
        shrimp = { Id = 'shrimp', SourceId = 17, Name = '虾米', Type = '食物', BasePrice = 4, source = '物品表!R18', implemented = true, EatPercent = 15, Icon = 'official://image/11164' },
        riverShrimp = { Id = 'riverShrimp', SourceId = 18, Name = '沼虾', Type = '食物', BasePrice = 10, source = '物品表!R19', implemented = true, EatPercent = 20, Icon = 'official://image/11164' },
        crayfish = { Id = 'crayfish', SourceId = 19, Name = '小龙虾', Type = '食物', BasePrice = 12, source = '物品表!R20', implemented = true, EatPercent = 20, Icon = 'official://image/11164' },
        bostonLobster = { Id = 'bostonLobster', SourceId = 20, Name = '波龙', Type = '食物', BasePrice = 15, source = '物品表!R21', implemented = true, EatPercent = 25, Icon = 'official://image/11164' },
        aussieLobster = { Id = 'aussieLobster', SourceId = 21, Name = '澳龙', Type = '食物', BasePrice = 18, source = '物品表!R22', implemented = true, EatPercent = 25, Icon = 'official://image/11164' },
        milkLobster = { Id = 'milkLobster', SourceId = 22, Name = '奶龙', Type = '食物', BasePrice = 21, source = '物品表!R23', implemented = true, EatPercent = 30, Icon = 'official://image/11164' },
        rareShrimp = { Id = 'rareShrimp', SourceId = 23, Name = '极品虾米', Type = '极品食物', BasePrice = 4, source = '物品表!R24', implemented = true, EatPercent = 15, Icon = 'official://image/11164' },
        rareRiverShrimp = { Id = 'rareRiverShrimp', SourceId = 24, Name = '极品沼虾', Type = '极品食物', BasePrice = 10, source = '物品表!R25', implemented = true, EatPercent = 20, Icon = 'official://image/11164' },
        rareCrayfish = { Id = 'rareCrayfish', SourceId = 25, Name = '极品小龙虾', Type = '极品食物', BasePrice = 12, source = '物品表!R26', implemented = true, EatPercent = 20, Icon = 'official://image/11164' },
        rareBostonLobster = { Id = 'rareBostonLobster', SourceId = 26, Name = '极品波龙', Type = '极品食物', BasePrice = 15, source = '物品表!R27', implemented = true, EatPercent = 25, Icon = 'official://image/11164' },
        rareAussieLobster = { Id = 'rareAussieLobster', SourceId = 27, Name = '极品澳龙', Type = '极品食物', BasePrice = 18, source = '物品表!R28', implemented = true, EatPercent = 25, Icon = 'official://image/11164' },
        rareMilkLobster = { Id = 'rareMilkLobster', SourceId = 28, Name = '极品奶龙', Type = '极品食物', BasePrice = 21, source = '物品表!R29', implemented = true, EatPercent = 30, Icon = 'official://image/11164' },
        item29 = { Id = 'item29', SourceId = 29, Name = '虾钳', Type = '食物', BasePrice = 50, source = '物品表!R30', implemented = false, EatPercent = 50 },
        item30 = { Id = 'item30', SourceId = 30, Name = '龙角', Type = '食物', BasePrice = 75, source = '物品表!R31', implemented = false, EatPercent = 100 },
        item31 = { Id = 'item31', SourceId = 31, Name = '虾尾', Type = '极品食物', BasePrice = 50, source = '物品表!R32', implemented = false, EatPercent = 50 },
        item32 = { Id = 'item32', SourceId = 32, Name = '龙筋', Type = '极品食物', BasePrice = 100, source = '物品表!R33', implemented = false, EatPercent = 100 },
        -- 蟹湖鱼获
        item33 = { Id = 'item33', SourceId = 33, Name = '蟛蜞', Type = '食物', BasePrice = 5, source = '物品表!R34', implemented = false, EatPercent = 15 },
        item34 = { Id = 'item34', SourceId = 34, Name = '寄居蟹', Type = '食物', BasePrice = 10, source = '物品表!R35', implemented = false, EatPercent = 20 },
        item35 = { Id = 'item35', SourceId = 35, Name = '大闸蟹', Type = '食物', BasePrice = 20, source = '物品表!R36', implemented = false, EatPercent = 20 },
        item36 = { Id = 'item36', SourceId = 36, Name = '梭子蟹', Type = '食物', BasePrice = 25, source = '物品表!R37', implemented = false, EatPercent = 25 },
        item37 = { Id = 'item37', SourceId = 37, Name = '青蟹', Type = '食物', BasePrice = 30, source = '物品表!R38', implemented = false, EatPercent = 25 },
        item38 = { Id = 'item38', SourceId = 38, Name = '面包蟹', Type = '食物', BasePrice = 40, source = '物品表!R39', implemented = false, EatPercent = 30 },
        item39 = { Id = 'item39', SourceId = 39, Name = '极品蟛蜞', Type = '极品食物', BasePrice = 5, source = '物品表!R40', implemented = false, EatPercent = 15 },
        item40 = { Id = 'item40', SourceId = 40, Name = '极品寄居蟹', Type = '极品食物', BasePrice = 10, source = '物品表!R41', implemented = false, EatPercent = 20 },
        item41 = { Id = 'item41', SourceId = 41, Name = '极品大闸蟹', Type = '极品食物', BasePrice = 20, source = '物品表!R42', implemented = false, EatPercent = 20 },
        item42 = { Id = 'item42', SourceId = 42, Name = '极品梭子蟹', Type = '极品食物', BasePrice = 25, source = '物品表!R43', implemented = false, EatPercent = 25 },
        item43 = { Id = 'item43', SourceId = 43, Name = '极品青蟹', Type = '极品食物', BasePrice = 30, source = '物品表!R44', implemented = false, EatPercent = 25 },
        item44 = { Id = 'item44', SourceId = 44, Name = '极品面包蟹', Type = '极品食物', BasePrice = 40, source = '物品表!R45', implemented = false, EatPercent = 30 },
        item45 = { Id = 'item45', SourceId = 45, Name = '蟹腿', Type = '食物', BasePrice = 75, source = '物品表!R46', implemented = false, EatPercent = 50 },
        item46 = { Id = 'item46', SourceId = 46, Name = '蟹钳', Type = '食物', BasePrice = 150, source = '物品表!R47', implemented = false, EatPercent = 100 },
        item47 = { Id = 'item47', SourceId = 47, Name = '蟹壳', Type = '极品食物', BasePrice = 100, source = '物品表!R48', implemented = false, EatPercent = 50 },
        item48 = { Id = 'item48', SourceId = 48, Name = '蟹眼', Type = '极品食物', BasePrice = 200, source = '物品表!R49', implemented = false, EatPercent = 100 },
        -- 树林岛鱼获
        item49 = { Id = 'item49', SourceId = 49, Name = '海胆', Type = '食物', BasePrice = 10, source = '物品表!R50', implemented = false, EatPercent = 15 },
        item50 = { Id = 'item50', SourceId = 50, Name = '比目鱼', Type = '食物', BasePrice = 20, source = '物品表!R51', implemented = false, EatPercent = 20 },
        item51 = { Id = 'item51', SourceId = 51, Name = '三文鱼', Type = '食物', BasePrice = 40, source = '物品表!R52', implemented = false, EatPercent = 20 },
        item52 = { Id = 'item52', SourceId = 52, Name = '翻车鲀', Type = '食物', BasePrice = 50, source = '物品表!R53', implemented = false, EatPercent = 25 },
        item53 = { Id = 'item53', SourceId = 53, Name = '鳐鱼', Type = '食物', BasePrice = 60, source = '物品表!R54', implemented = false, EatPercent = 25 },
        item54 = { Id = 'item54', SourceId = 54, Name = '旗鱼', Type = '食物', BasePrice = 80, source = '物品表!R55', implemented = false, EatPercent = 30 },
        item55 = { Id = 'item55', SourceId = 55, Name = '极品海胆', Type = '极品食物', BasePrice = 10, source = '物品表!R56', implemented = false, EatPercent = 15 },
        item56 = { Id = 'item56', SourceId = 56, Name = '极品比目鱼', Type = '极品食物', BasePrice = 20, source = '物品表!R57', implemented = false, EatPercent = 20 },
        item57 = { Id = 'item57', SourceId = 57, Name = '极品三文鱼', Type = '极品食物', BasePrice = 40, source = '物品表!R58', implemented = false, EatPercent = 20 },
        item58 = { Id = 'item58', SourceId = 58, Name = '极品翻车鲀', Type = '极品食物', BasePrice = 50, source = '物品表!R59', implemented = false, EatPercent = 25 },
        item59 = { Id = 'item59', SourceId = 59, Name = '极品鳐鱼', Type = '极品食物', BasePrice = 60, source = '物品表!R60', implemented = false, EatPercent = 25 },
        item60 = { Id = 'item60', SourceId = 60, Name = '极品旗鱼', Type = '极品食物', BasePrice = 80, source = '物品表!R61', implemented = false, EatPercent = 30 },
        item61 = { Id = 'item61', SourceId = 61, Name = '剑鱼肉', Type = '食物', BasePrice = 150, source = '物品表!R62', implemented = false, EatPercent = 50 },
        item62 = { Id = 'item62', SourceId = 62, Name = '鱼翅', Type = '食物', BasePrice = 300, source = '物品表!R63', implemented = false, EatPercent = 100 },
        item63 = { Id = 'item63', SourceId = 63, Name = '鱼剑', Type = '极品食物', BasePrice = 200, source = '物品表!R64', implemented = false, EatPercent = 50 },
        item64 = { Id = 'item64', SourceId = 64, Name = '三联鲨鱼头', Type = '极品食物', BasePrice = 500, source = '物品表!R65', implemented = false, SourceName = '三连鲨鱼头', DecisionSource = '策划案已确认结论.md#Q10', EatPercent = 100 },
        -- 沙滩岛鱼获
        item65 = { Id = 'item65', SourceId = 65, Name = '海参', Type = '食物', BasePrice = 100, source = '物品表!R66', implemented = false, EatPercent = 15 },
        item66 = { Id = 'item66', SourceId = 66, Name = '海兔', Type = '食物', BasePrice = 150, source = '物品表!R67', implemented = false, EatPercent = 20 },
        item67 = { Id = 'item67', SourceId = 67, Name = '海马', Type = '食物', BasePrice = 200, source = '物品表!R68', implemented = false, EatPercent = 20 },
        item68 = { Id = 'item68', SourceId = 68, Name = '海狗', Type = '食物', BasePrice = 250, source = '物品表!R69', implemented = false, EatPercent = 25 },
        item69 = { Id = 'item69', SourceId = 69, Name = '海狮', Type = '食物', BasePrice = 300, source = '物品表!R70', implemented = false, EatPercent = 25 },
        item70 = { Id = 'item70', SourceId = 70, Name = '海牛', Type = '食物', BasePrice = 350, source = '物品表!R71', implemented = false, EatPercent = 30 },
        item71 = { Id = 'item71', SourceId = 71, Name = '极品海参', Type = '极品食物', BasePrice = 100, source = '物品表!R72', implemented = false, EatPercent = 15 },
        item72 = { Id = 'item72', SourceId = 72, Name = '极品海兔', Type = '极品食物', BasePrice = 150, source = '物品表!R73', implemented = false, EatPercent = 20 },
        item73 = { Id = 'item73', SourceId = 73, Name = '极品海马', Type = '极品食物', BasePrice = 200, source = '物品表!R74', implemented = false, EatPercent = 20 },
        item74 = { Id = 'item74', SourceId = 74, Name = '极品海狗', Type = '极品食物', BasePrice = 250, source = '物品表!R75', implemented = false, EatPercent = 25 },
        item75 = { Id = 'item75', SourceId = 75, Name = '极品海狮', Type = '极品食物', BasePrice = 300, source = '物品表!R76', implemented = false, EatPercent = 25 },
        item76 = { Id = 'item76', SourceId = 76, Name = '极品海牛', Type = '极品食物', BasePrice = 350, source = '物品表!R77', implemented = false, EatPercent = 30 },
        item77 = { Id = 'item77', SourceId = 77, Name = '海象牙', Type = '食物', BasePrice = 750, source = '物品表!R78', implemented = false, EatPercent = 50 },
        item78 = { Id = 'item78', SourceId = 78, Name = '虎爪', Type = '食物', BasePrice = 1000, source = '物品表!R79', implemented = false, EatPercent = 100 },
        item79 = { Id = 'item79', SourceId = 79, Name = '海象尾', Type = '极品食物', BasePrice = 800, source = '物品表!R80', implemented = false, EatPercent = 50 },
        item80 = { Id = 'item80', SourceId = 80, Name = '虎头', Type = '极品食物', BasePrice = 1500, source = '物品表!R81', implemented = false, EatPercent = 100 },
        -- 礁石岛鱼获
        item81 = { Id = 'item81', SourceId = 81, Name = '巨脉蜻蜓', Type = '食物', BasePrice = 200, source = '物品表!R82', implemented = false, EatPercent = 15 },
        item82 = { Id = 'item82', SourceId = 82, Name = '企鹅', Type = '食物', BasePrice = 250, source = '物品表!R83', implemented = false, EatPercent = 20 },
        item83 = { Id = 'item83', SourceId = 83, Name = '飞鱼', Type = '食物', BasePrice = 300, source = '物品表!R84', implemented = false, EatPercent = 20 },
        item84 = { Id = 'item84', SourceId = 84, Name = '海鸥', Type = '食物', BasePrice = 350, source = '物品表!R85', implemented = false, EatPercent = 25 },
        item85 = { Id = 'item85', SourceId = 85, Name = '军舰鸟', Type = '食物', BasePrice = 400, source = '物品表!R86', implemented = false, EatPercent = 25 },
        item86 = { Id = 'item86', SourceId = 86, Name = '信天翁', Type = '食物', BasePrice = 450, source = '物品表!R87', implemented = false, EatPercent = 30 },
        item87 = { Id = 'item87', SourceId = 87, Name = '极品巨脉蜻蜓', Type = '极品食物', BasePrice = 200, source = '物品表!R88', implemented = false, EatPercent = 15 },
        item88 = { Id = 'item88', SourceId = 88, Name = '极品企鹅', Type = '极品食物', BasePrice = 250, source = '物品表!R89', implemented = false, EatPercent = 20 },
        item89 = { Id = 'item89', SourceId = 89, Name = '极品飞鱼', Type = '极品食物', BasePrice = 300, source = '物品表!R90', implemented = false, EatPercent = 20 },
        item90 = { Id = 'item90', SourceId = 90, Name = '极品海鸥', Type = '极品食物', BasePrice = 350, source = '物品表!R91', implemented = false, EatPercent = 25 },
        item91 = { Id = 'item91', SourceId = 91, Name = '极品军舰鸟', Type = '极品食物', BasePrice = 400, source = '物品表!R92', implemented = false, EatPercent = 25 },
        item92 = { Id = 'item92', SourceId = 92, Name = '极品信天翁', Type = '极品食物', BasePrice = 450, source = '物品表!R93', implemented = false, EatPercent = 30 },
        item93 = { Id = 'item93', SourceId = 93, Name = '鹰翅膀', Type = '食物', BasePrice = 1000, source = '物品表!R94', implemented = false, EatPercent = 50 },
        item94 = { Id = 'item94', SourceId = 94, Name = '翼龙之翼', Type = '食物', BasePrice = 1500, source = '物品表!R95', implemented = false, EatPercent = 100 },
        item95 = { Id = 'item95', SourceId = 95, Name = '鹰头', Type = '极品食物', BasePrice = 1500, source = '物品表!R96', implemented = false, EatPercent = 50 },
        item96 = { Id = 'item96', SourceId = 96, Name = '翼龙头', Type = '极品食物', BasePrice = 2000, source = '物品表!R97', implemented = false, EatPercent = 100 },
        -- 火山岛鱼获
        item97 = { Id = 'item97', SourceId = 97, Name = '章鱼', Type = '食物', BasePrice = 500, source = '物品表!R98', implemented = false, EatPercent = 15 },
        item98 = { Id = 'item98', SourceId = 98, Name = '海星', Type = '食物', BasePrice = 600, source = '物品表!R99', implemented = false, EatPercent = 20 },
        item99 = { Id = 'item99', SourceId = 99, Name = '海绵', Type = '食物', BasePrice = 700, source = '物品表!R100', implemented = false, EatPercent = 20 },
        item100 = { Id = 'item100', SourceId = 100, Name = '鱼龙', Type = '食物', BasePrice = 800, source = '物品表!R101', implemented = false, EatPercent = 25 },
        item101 = { Id = 'item101', SourceId = 101, Name = '蛇颈龙', Type = '食物', BasePrice = 900, source = '物品表!R102', implemented = false, EatPercent = 25 },
        item102 = { Id = 'item102', SourceId = 102, Name = '美人鱼', Type = '食物', BasePrice = 1000, source = '物品表!R103', implemented = false, EatPercent = 30 },
        item103 = { Id = 'item103', SourceId = 103, Name = '极品章鱼', Type = '极品食物', BasePrice = 500, source = '物品表!R104', implemented = false, EatPercent = 15 },
        item104 = { Id = 'item104', SourceId = 104, Name = '极品海星', Type = '极品食物', BasePrice = 600, source = '物品表!R105', implemented = false, EatPercent = 20 },
        item105 = { Id = 'item105', SourceId = 105, Name = '极品海绵', Type = '极品食物', BasePrice = 700, source = '物品表!R106', implemented = false, EatPercent = 20 },
        item106 = { Id = 'item106', SourceId = 106, Name = '极品鱼龙', Type = '极品食物', BasePrice = 800, source = '物品表!R107', implemented = false, EatPercent = 25 },
        item107 = { Id = 'item107', SourceId = 107, Name = '极品蛇颈龙', Type = '极品食物', BasePrice = 900, source = '物品表!R108', implemented = false, EatPercent = 25 },
        item108 = { Id = 'item108', SourceId = 108, Name = '极品美人鱼', Type = '极品食物', BasePrice = 1000, source = '物品表!R109', implemented = false, EatPercent = 30 },
        item109 = { Id = 'item109', SourceId = 109, Name = '沧龙翅', Type = '食物', BasePrice = 2000, source = '物品表!R110', implemented = false, SourceName = '沧龙肉', DecisionSource = '策划案已确认结论.md#Q10', EatPercent = 50 },
        item110 = { Id = 'item110', SourceId = 110, Name = '哥斯拉爪', Type = '食物', BasePrice = 5000, source = '物品表!R111', implemented = false, EatPercent = 100 },
        item111 = { Id = 'item111', SourceId = 111, Name = '沧龙尾', Type = '极品食物', BasePrice = 4000, source = '物品表!R112', implemented = false, SourceName = '沧龙头', DecisionSource = '策划案已确认结论.md#Q10', EatPercent = 50 },
        item112 = { Id = 'item112', SourceId = 112, Name = '哥斯拉头', Type = '极品食物', BasePrice = 10000, source = '物品表!R113', implemented = false, EatPercent = 100 },
        -- 普通鱼饵
        worm = { Id = 'worm', SourceId = 113, Name = '蚯蚓', Type = '鱼饵', BasePrice = 1, source = '物品表!R114', implemented = true, EatPercent = 5, Container = 'bait', Icon = 'official://image/14066' },
        sausage = { Id = 'sausage', SourceId = 114, Name = '香肠', Type = '鱼饵', BasePrice = 2, source = '物品表!R115', implemented = true, EatPercent = 5, Container = 'bait', Icon = 'official://image/14066' },
        item115 = { Id = 'item115', SourceId = 115, Name = '鲱鱼罐头', Type = '鱼饵', BasePrice = 3, source = '物品表!R116', implemented = false, EatPercent = 5, Container = 'bait' },
        item116 = { Id = 'item116', SourceId = 116, Name = '蚂蟥', Type = '鱼饵', BasePrice = 4, source = '物品表!R117', implemented = false, EatPercent = 5, Container = 'bait' },
        item117 = { Id = 'item117', SourceId = 117, Name = '椰子', Type = '鱼饵', BasePrice = 5, source = '物品表!R118', implemented = false, EatPercent = 5, Container = 'bait' },
        item118 = { Id = 'item118', SourceId = 118, Name = '小海龟', Type = '鱼饵', BasePrice = 6, source = '物品表!R119', implemented = false, EatPercent = 5, Container = 'bait' },
        item119 = { Id = 'item119', SourceId = 119, Name = '科技假饵', Type = '鱼饵', BasePrice = 7, source = '物品表!R120', implemented = false, EatPercent = -20, Container = 'bait' },
        -- 首领饵
        duck = { Id = 'duck', SourceId = 120, Name = '鸭子', Type = '鱼饵', BasePrice = 10, source = '物品表!R121', implemented = true, EatPercent = 10, BossBait = true, Icon = 'official://image/11154' },
        item121 = { Id = 'item121', SourceId = 121, Name = '夜明珠', Type = '鱼饵', BasePrice = 100, source = '物品表!R122', implemented = false, EatPercent = -20, BossBait = true },
        item122 = { Id = 'item122', SourceId = 122, Name = '绿色钞票', Type = '鱼饵', BasePrice = 100, source = '物品表!R123', implemented = false, EatPercent = -10, BossBait = true },
        item123 = { Id = 'item123', SourceId = 123, Name = '牛腿', Type = '鱼饵', BasePrice = 25, source = '物品表!R124', implemented = false, EatPercent = 40, BossBait = true },
        item124 = { Id = 'item124', SourceId = 124, Name = '海豹', Type = '鱼饵', BasePrice = 50, source = '物品表!R125', implemented = false, EatPercent = 40, BossBait = true },
        item125 = { Id = 'item125', SourceId = 125, Name = '羊', Type = '鱼饵', BasePrice = 75, source = '物品表!R126', implemented = false, EatPercent = 40, BossBait = true },
        item126 = { Id = 'item126', SourceId = 126, Name = '核废料桶', Type = '鱼饵', BasePrice = 100, source = '物品表!R127', implemented = false, EatPercent = -99, BossBait = true },
        -- 鱼竿
        starterRod = { Id = 'starterRod', SourceId = 127, Name = '新手鱼竿', Type = '鱼竿', BasePrice = 3, source = '物品表!R128', implemented = true, Level = 1, Icon = 'official://image/12024' },
        shrimpRod = { Id = 'shrimpRod', SourceId = 128, Name = '钓虾竿', Type = '鱼竿', BasePrice = 6, source = '物品表!R129', implemented = true, Level = 2, Icon = 'official://image/12024' },
        crabRod = { Id = 'crabRod', SourceId = 129, Name = '捕蟹竿', Type = '鱼竿', BasePrice = 13, source = '物品表!R130', implemented = true, Level = 3, Icon = 'official://image/12024' },
        normalRod = { Id = 'normalRod', SourceId = 130, Name = '普通鱼竿', Type = '鱼竿', BasePrice = 25, source = '物品表!R131', implemented = true, Level = 4, Icon = 'official://image/12024' },
        proRod = { Id = 'proRod', SourceId = 131, Name = '专业鱼竿', Type = '鱼竿', BasePrice = 50, source = '物品表!R132', implemented = true, Level = 5, Icon = 'official://image/12024' },
        airforceRod = { Id = 'airforceRod', SourceId = 132, Name = '空军之竿', Type = '鱼竿', BasePrice = 100, source = '物品表!R133', implemented = true, Level = 6, Icon = 'official://image/12024' },
        unscientificRod = { Id = 'unscientificRod', SourceId = 133, Name = '不科学鱼竿', Type = '鱼竿', BasePrice = 250, source = '物品表!R134', implemented = true, Level = 7, Icon = 'official://image/12024' },
        -- 商店武器与爆炸物
        item134 = { Id = 'item134', SourceId = 134, Name = '指虎', Type = '近战武器', BasePrice = 13, source = '物品表!R135', implemented = false },
        item135 = { Id = 'item135', SourceId = 135, Name = '匕首', Type = '近战武器', BasePrice = 25, source = '物品表!R136', implemented = false },
        item136 = { Id = 'item136', SourceId = 136, Name = '斧头', Type = '近战武器', BasePrice = 50, source = '物品表!R137', implemented = false },
        item137 = { Id = 'item137', SourceId = 137, Name = '手枪', Type = '远程武器', BasePrice = 75, source = '物品表!R138', implemented = false },
        item138 = { Id = 'item138', SourceId = 138, Name = '霰弹枪', Type = '远程武器', BasePrice = 100, source = '物品表!R139', implemented = false },
        item139 = { Id = 'item139', SourceId = 139, Name = '冲锋枪', Type = '远程武器', BasePrice = 250, source = '物品表!R140', implemented = false },
        item140 = { Id = 'item140', SourceId = 140, Name = '自动步枪', Type = '远程武器', BasePrice = 500, source = '物品表!R141', implemented = false },
        item141 = { Id = 'item141', SourceId = 141, Name = '狙击枪', Type = '远程武器', BasePrice = 1000, source = '物品表!R142', implemented = false },
        item142 = { Id = 'item142', SourceId = 142, Name = '火箭筒', Type = '远程武器', BasePrice = 1250, source = '物品表!R143', implemented = false },
        item143 = { Id = 'item143', SourceId = 143, Name = '鞭炮', Type = '爆炸物', BasePrice = 12, source = '物品表!R144', implemented = false },
        item144 = { Id = 'item144', SourceId = 144, Name = '手雷', Type = '爆炸物', BasePrice = 25, source = '物品表!R145', implemented = false },
        item145 = { Id = 'item145', SourceId = 145, Name = '炸药', Type = '爆炸物', BasePrice = 50, source = '物品表!R146', implemented = false },
        -- 船票
        shrimpTicket = { Id = 'shrimpTicket', SourceId = 146, Name = '虾池船票', Type = '过关道具', BasePrice = 1, source = '物品表!R147', implemented = true, SourceName = '虾池车票', DecisionSource = 'CONTEXT.md#船票', Icon = 'official://image/14105' },
        item147 = { Id = 'item147', SourceId = 147, Name = '蟹湖船票', Type = '过关道具', BasePrice = 1, source = '物品表!R148', implemented = false, SourceName = '蟹湖车票', DecisionSource = 'CONTEXT.md#船票' },
        item148 = { Id = 'item148', SourceId = 148, Name = '树林岛船票', Type = '过关道具', BasePrice = 1, source = '物品表!R149', implemented = false },
        item149 = { Id = 'item149', SourceId = 149, Name = '沙滩岛船票', Type = '过关道具', BasePrice = 1, source = '物品表!R150', implemented = false },
        item150 = { Id = 'item150', SourceId = 150, Name = '礁石岛船票', Type = '过关道具', BasePrice = 1, source = '物品表!R151', implemented = false },
        item151 = { Id = 'item151', SourceId = 151, Name = '火山岛船票', Type = '过关道具', BasePrice = 1, source = '物品表!R152', implemented = false },
        -- 独立武器大奖
        item152 = { Id = 'item152', SourceId = 152, Name = '淬毒匕首', Type = '近战武器', BasePrice = 1, source = '物品表!R153', implemented = false, SourceDescription = '近战武器，对命中目标造成15点伤害，攻击间隔0.5秒。命中目标每秒受到1点中毒伤害，持续3秒。中毒最多叠加5层。' },
        item153 = { Id = 'item153', SourceId = 153, Name = '秘银匕首', Type = '近战武器', BasePrice = 1, source = '物品表!R154', implemented = false, SourceDescription = '近战武器，对命中目标造成18点伤害，攻击间隔0.5秒。' },
        item154 = { Id = 'item154', SourceId = 154, Name = '黄金匕首', Type = '近战武器', BasePrice = 1, source = '物品表!R155', implemented = false, SourceDescription = '近战武器，对命中目标造成18点伤害，攻击间隔0.5秒。' },
        item155 = { Id = 'item155', SourceId = 155, Name = '黑曜石匕首', Type = '近战武器', BasePrice = 1, source = '物品表!R156', implemented = false, SourceDescription = '近战武器，对命中目标造成18点伤害，攻击间隔0.5秒。' },
        item156 = { Id = 'item156', SourceId = 156, Name = '锯齿匕首', Type = '近战武器', BasePrice = 1, source = '物品表!R157', implemented = false, SourceDescription = '近战武器，对命中目标造成18点伤害，攻击间隔0.5秒。' },
        item157 = { Id = 'item157', SourceId = 157, Name = '银斧', Type = '近战武器', BasePrice = 1, source = '物品表!R158', implemented = false, SourceDescription = '近战武器，对命中目标造成52点伤害，攻击间隔1秒。' },
        item158 = { Id = 'item158', SourceId = 158, Name = '金斧', Type = '近战武器', BasePrice = 1, source = '物品表!R159', implemented = false, SourceDescription = '近战武器，对命中目标造成52点伤害，攻击间隔1秒。' },
        item159 = { Id = 'item159', SourceId = 159, Name = '炽焰战斧', Type = '近战武器', BasePrice = 1, source = '物品表!R160', implemented = false, SourceDescription = '近战武器，对命中目标造成40点伤害，攻击间隔1秒。命中目标每秒受到4点灼烧伤害，持续3秒。灼烧最多叠加5层。' },
        item160 = { Id = 'item160', SourceId = 160, Name = '血吼', Type = '近战武器', BasePrice = 1, source = '物品表!R161', implemented = false, SourceDescription = '近战武器，对命中目标造成60点伤害，攻击间隔1秒。' },
        item161 = { Id = 'item161', SourceId = 161, Name = '无坚不摧之力', Type = '近战武器', BasePrice = 1, source = '物品表!R162', implemented = false, SourceDescription = '近战武器，对命中目标造成68点伤害，攻击间隔1秒。' },
        item162 = { Id = 'item162', SourceId = 162, Name = '沙漠之鹰', Type = '远程武器', BasePrice = 1, source = '物品表!R163', implemented = false, SourceDescription = '手枪，对命中目标造成15点伤害，射击间隔1秒。基础弹容量15.' },
        item163 = { Id = 'item163', SourceId = 163, Name = '霜之新星', Type = '远程武器', BasePrice = 1, source = '物品表!R164', implemented = false, SourceDescription = '手枪，对命中目标造成10点伤害，射击间隔1秒。基础弹容量10，命中目标霜冻移动速度降低30%，持续3秒。霜冻效果不叠加。' },
        item164 = { Id = 'item164', SourceId = 164, Name = '雷霆之力', Type = '远程武器', BasePrice = 1, source = '物品表!R165', implemented = false, SourceDescription = '手枪，对命中目标造成10点伤害，射击间隔1秒。基础弹容量10，命中目标麻痹无法行动，持续0.5秒。麻痹效果不叠加。' },
        item165 = { Id = 'item165', SourceId = 165, Name = '黄金AK47', Type = '远程武器', BasePrice = 1, source = '物品表!R166', implemented = false, SourceDescription = '自动步枪，对命中目标造成30点伤害，射击间隔0.2秒。基础弹容量30。' },
        item166 = { Id = 'item166', SourceId = 166, Name = '连发火箭筒', Type = '远程武器', BasePrice = 1, source = '物品表!R167', implemented = false, SourceDescription = '火箭筒，对命中目标造成500点伤害。周围5米范围收到100点爆炸伤害，射击间隔1秒。基础弹容量10。' },
        -- 属性、特殊与自救道具
        item167 = { Id = 'item167', SourceId = 167, Name = '加速药水', Type = '属性道具', BasePrice = 1, source = '物品表!R168', implemented = false, SourceDescription = '吃掉增加移动速度，最多吃20个' },
        item168 = { Id = 'item168', SourceId = 168, Name = '变大药水', Type = '属性道具', BasePrice = 1, source = '物品表!R169', implemented = false, SourceDescription = '抽奖获得，吃掉增加体型和血量，最多吃10个' },
        item169 = { Id = 'item169', SourceId = 169, Name = '风神之翼', Type = '特殊道具', BasePrice = 1, source = '物品表!R170', implemented = false, SourceDescription = '抽奖获得，使用时可以飞行' },
        item170 = { Id = 'item170', SourceId = 170, Name = '哥斯拉', Type = '特殊道具', BasePrice = 1, source = '物品表!R171', implemented = false, SourceDescription = '抽奖获得，使用时更换皮肤，可以使用原子吐息' },
        item171 = { Id = 'item171', SourceId = 171, Name = '肾上腺素', Type = '自救道具', BasePrice = 1, source = '物品表!R172', implemented = false, SourceDescription = '购买获得，自救使用。' },
    },
    SourceIdMap = {
        [1] = 'tilapia',
        [2] = 'carp',
        [3] = 'knifeFish',
        [4] = 'bass',
        [5] = 'catfish',
        [6] = 'goldfish',
        [7] = 'item7',
        [8] = 'item8',
        [9] = 'item9',
        [10] = 'item10',
        [11] = 'item11',
        [12] = 'item12',
        [13] = 'eelMeat',
        [14] = 'garMeat',
        [15] = 'eelHead',
        [16] = 'garHead',
        [17] = 'shrimp',
        [18] = 'riverShrimp',
        [19] = 'crayfish',
        [20] = 'bostonLobster',
        [21] = 'aussieLobster',
        [22] = 'milkLobster',
        [23] = 'rareShrimp',
        [24] = 'rareRiverShrimp',
        [25] = 'rareCrayfish',
        [26] = 'rareBostonLobster',
        [27] = 'rareAussieLobster',
        [28] = 'rareMilkLobster',
        [29] = 'item29',
        [30] = 'item30',
        [31] = 'item31',
        [32] = 'item32',
        [33] = 'item33',
        [34] = 'item34',
        [35] = 'item35',
        [36] = 'item36',
        [37] = 'item37',
        [38] = 'item38',
        [39] = 'item39',
        [40] = 'item40',
        [41] = 'item41',
        [42] = 'item42',
        [43] = 'item43',
        [44] = 'item44',
        [45] = 'item45',
        [46] = 'item46',
        [47] = 'item47',
        [48] = 'item48',
        [49] = 'item49',
        [50] = 'item50',
        [51] = 'item51',
        [52] = 'item52',
        [53] = 'item53',
        [54] = 'item54',
        [55] = 'item55',
        [56] = 'item56',
        [57] = 'item57',
        [58] = 'item58',
        [59] = 'item59',
        [60] = 'item60',
        [61] = 'item61',
        [62] = 'item62',
        [63] = 'item63',
        [64] = 'item64',
        [65] = 'item65',
        [66] = 'item66',
        [67] = 'item67',
        [68] = 'item68',
        [69] = 'item69',
        [70] = 'item70',
        [71] = 'item71',
        [72] = 'item72',
        [73] = 'item73',
        [74] = 'item74',
        [75] = 'item75',
        [76] = 'item76',
        [77] = 'item77',
        [78] = 'item78',
        [79] = 'item79',
        [80] = 'item80',
        [81] = 'item81',
        [82] = 'item82',
        [83] = 'item83',
        [84] = 'item84',
        [85] = 'item85',
        [86] = 'item86',
        [87] = 'item87',
        [88] = 'item88',
        [89] = 'item89',
        [90] = 'item90',
        [91] = 'item91',
        [92] = 'item92',
        [93] = 'item93',
        [94] = 'item94',
        [95] = 'item95',
        [96] = 'item96',
        [97] = 'item97',
        [98] = 'item98',
        [99] = 'item99',
        [100] = 'item100',
        [101] = 'item101',
        [102] = 'item102',
        [103] = 'item103',
        [104] = 'item104',
        [105] = 'item105',
        [106] = 'item106',
        [107] = 'item107',
        [108] = 'item108',
        [109] = 'item109',
        [110] = 'item110',
        [111] = 'item111',
        [112] = 'item112',
        [113] = 'worm',
        [114] = 'sausage',
        [115] = 'item115',
        [116] = 'item116',
        [117] = 'item117',
        [118] = 'item118',
        [119] = 'item119',
        [120] = 'duck',
        [121] = 'item121',
        [122] = 'item122',
        [123] = 'item123',
        [124] = 'item124',
        [125] = 'item125',
        [126] = 'item126',
        [127] = 'starterRod',
        [128] = 'shrimpRod',
        [129] = 'crabRod',
        [130] = 'normalRod',
        [131] = 'proRod',
        [132] = 'airforceRod',
        [133] = 'unscientificRod',
        [134] = 'item134',
        [135] = 'item135',
        [136] = 'item136',
        [137] = 'item137',
        [138] = 'item138',
        [139] = 'item139',
        [140] = 'item140',
        [141] = 'item141',
        [142] = 'item142',
        [143] = 'item143',
        [144] = 'item144',
        [145] = 'item145',
        [146] = 'shrimpTicket',
        [147] = 'item147',
        [148] = 'item148',
        [149] = 'item149',
        [150] = 'item150',
        [151] = 'item151',
        [152] = 'item152',
        [153] = 'item153',
        [154] = 'item154',
        [155] = 'item155',
        [156] = 'item156',
        [157] = 'item157',
        [158] = 'item158',
        [159] = 'item159',
        [160] = 'item160',
        [161] = 'item161',
        [162] = 'item162',
        [163] = 'item163',
        [164] = 'item164',
        [165] = 'item165',
        [166] = 'item166',
        [167] = 'item167',
        [168] = 'item168',
        [169] = 'item169',
        [170] = 'item170',
        [171] = 'item171',
    },
    LegacyIdMap = {
        tilapia = 'tilapia',
        carp = 'carp',
        knifeFish = 'knifeFish',
        bass = 'bass',
        catfish = 'catfish',
        goldfish = 'goldfish',
        eelMeat = 'eelMeat',
        garMeat = 'garMeat',
        eelHead = 'eelHead',
        garHead = 'garHead',
        shrimp = 'shrimp',
        riverShrimp = 'riverShrimp',
        crayfish = 'crayfish',
        bostonLobster = 'bostonLobster',
        aussieLobster = 'aussieLobster',
        milkLobster = 'milkLobster',
        rareShrimp = 'rareShrimp',
        rareRiverShrimp = 'rareRiverShrimp',
        rareCrayfish = 'rareCrayfish',
        rareBostonLobster = 'rareBostonLobster',
        rareAussieLobster = 'rareAussieLobster',
        rareMilkLobster = 'rareMilkLobster',
        worm = 'worm',
        sausage = 'sausage',
        duck = 'duck',
        starterRod = 'starterRod',
        shrimpRod = 'shrimpRod',
        crabRod = 'crabRod',
        normalRod = 'normalRod',
        proRod = 'proRod',
        airforceRod = 'airforceRod',
        unscientificRod = 'unscientificRod',
        shrimpTicket = 'shrimpTicket',
    },
}
