-- 商店表 51 行中第 27 项作废；其余原序与编号用于当地新品置顶及稳定排序。
-- implemented：#130 起 50 行全部接入钓场商店（购买/强化/限购走 MgrShop + #123 持久协议）。
return {
    Currency = '金币',
    Pages = { '钓具', '武器', '升级', '金币' },
    Goods = {
        { number = 1, itemName = '科技假饵', itemKey = 'item119', description = '可以在火山岛钓到各种神奇生物的高科技。别吃！', minShopLevel = 7, page = '钓具', price = 7, purchaseLimit = 0, implemented = true, source = '商店表!R2' },
        { number = 2, itemName = '不科学鱼竿', itemKey = 'unscientificRod', description = '可以在火山岛钓到各种神奇生物的神奇钓竿。', minShopLevel = 7, page = '钓具', price = 500, purchaseLimit = 0, implemented = true, source = '商店表!R3' },
        { number = 3, itemName = '小海龟', itemKey = 'item118', description = '鸟儿们都爱小海龟。真没多少肉，你就别惦记了！', minShopLevel = 6, page = '钓具', price = 6, purchaseLimit = 0, implemented = true, source = '商店表!R4' },
        { number = 4, itemName = '空军之竿', itemKey = 'airforceRod', description = '虽然这竿对于钓鱼来说不太吉利，但有时候却很实用。', minShopLevel = 6, page = '钓具', price = 200, purchaseLimit = 0, implemented = true, source = '商店表!R5' },
        { number = 5, itemName = '椰子', itemKey = 'item117', description = '沙滩岛周围的动物们喜欢把椰子顶鼻子上。你吃就费劲了。', minShopLevel = 5, page = '钓具', price = 5, purchaseLimit = 0, implemented = true, source = '商店表!R6' },
        { number = 6, itemName = '专业鱼竿', itemKey = 'proRod', description = '相当专业的鱼竿，海里有什么都能钓的到。', minShopLevel = 5, page = '钓具', price = 100, purchaseLimit = 0, implemented = true, source = '商店表!R7' },
        { number = 7, itemName = '蚂蟥', itemKey = 'item116', description = '来自陆地的小肉条，是海鱼们的最爱。你不会也想尝尝吧？', minShopLevel = 4, page = '钓具', price = 4, purchaseLimit = 0, implemented = true, source = '商店表!R8' },
        { number = 8, itemName = '普通鱼竿', itemKey = 'normalRod', description = '看着普普通通的一根竿子，可上鱼可是杠杠的！', minShopLevel = 4, page = '钓具', price = 50, purchaseLimit = 0, implemented = true, source = '商店表!R9' },
        { number = 9, itemName = '鲱鱼罐头', itemKey = 'item115', description = '你也想试试？这臭哄哄的发酵鲱鱼只有螃蟹爱吃吧？', minShopLevel = 3, page = '钓具', price = 3, purchaseLimit = 0, implemented = true, source = '商店表!R10' },
        { number = 10, itemName = '捕蟹竿', itemKey = 'crabRod', description = '专业钓蟹用的竿子，买一根吧。', minShopLevel = 3, page = '钓具', price = 24, purchaseLimit = 0, implemented = true, source = '商店表!R11' },
        { number = 11, itemName = '香肠', itemKey = 'sausage', description = '香咸可口的香肠，虾子们也喜欢它。', minShopLevel = 2, page = '钓具', price = 2, purchaseLimit = 0, implemented = true, source = '商店表!R12' },
        { number = 12, itemName = '钓虾竿', itemKey = 'shrimpRod', description = '专业钓虾用的竿子，买一根吧。', minShopLevel = 2, page = '钓具', price = 12, purchaseLimit = 0, implemented = true, source = '商店表!R13' },
        { number = 13, itemName = '蚯蚓', itemKey = 'worm', description = '满地都能捡到的小肉条，你真的要买它吗？', minShopLevel = 1, page = '钓具', price = 1, purchaseLimit = 0, implemented = true, source = '商店表!R14' },
        { number = 14, itemName = '新手鱼竿', itemKey = 'starterRod', description = '下水是捞不到鱼的，你必须买它。', minShopLevel = 1, page = '钓具', price = 5, purchaseLimit = 0, implemented = true, source = '商店表!R15' },
        { number = 15, itemName = '炸药', itemKey = 'item145', description = '150伤害。拿起它，丢出去，boom！就这么简单。', minShopLevel = 6, page = '武器', price = 100, purchaseLimit = 0, implemented = true, source = '商店表!R16' },
        { number = 16, itemName = '手雷', itemKey = 'item144', description = '100伤害。拿起它，丢出去，𠳐！就这么简单。', minShopLevel = 4, page = '武器', price = 50, purchaseLimit = 0, implemented = true, source = '商店表!R17' },
        { number = 17, itemName = '鞭炮', itemKey = 'item143', description = '50伤害。拿起它，丢出去，嘣！就这么简单。', minShopLevel = 2, page = '武器', price = 24, purchaseLimit = 0, implemented = true, source = '商店表!R18' },
        { number = 18, itemName = '火箭筒', itemKey = 'item142', description = '对命中目标造成500点伤害。周围5米范围收到100点爆炸伤害。基础弹容量1。', minShopLevel = 7, page = '武器', price = 5000, purchaseLimit = 0, implemented = true, source = '商店表!R19' },
        { number = 19, itemName = '狙击枪', itemKey = 'item141', description = '对命中目标造成200点伤害，射击间隔1.5秒。基础弹容量5。', minShopLevel = 6, page = '武器', price = 2000, purchaseLimit = 0, implemented = true, source = '商店表!R20' },
        { number = 20, itemName = '自动步枪', itemKey = 'item140', description = '对命中目标造成20点伤害，射击间隔0.2秒。基础弹容量30。', minShopLevel = 5, page = '武器', price = 1000, purchaseLimit = 0, implemented = true, source = '商店表!R21' },
        { number = 21, itemName = '冲锋枪', itemKey = 'item139', description = '对命中目标造成13点伤害，射击间隔0.15秒。基础弹容量30。', minShopLevel = 4, page = '武器', price = 500, purchaseLimit = 0, implemented = true, source = '商店表!R22' },
        { number = 22, itemName = '霰弹枪', itemKey = 'item138', description = '每次打出5发子弹，每发命中造成20点伤害，射击间隔1.5秒。基础弹容量2.', minShopLevel = 3, page = '武器', price = 200, purchaseLimit = 0, implemented = true, source = '商店表!R23' },
        { number = 23, itemName = '手枪', itemKey = 'item137', description = '对命中目标造成10点伤害，射击间隔1秒。基础弹容量10.', minShopLevel = 2, page = '武器', price = 150, purchaseLimit = 0, implemented = true, source = '商店表!R24' },
        { number = 24, itemName = '斧头', itemKey = 'item136', description = '近战武器，对命中目标造成40点伤害，攻击间隔1秒。', minShopLevel = 2, page = '武器', price = 100, purchaseLimit = 0, implemented = true, source = '商店表!R25' },
        { number = 25, itemName = '匕首', itemKey = 'item135', description = '近战武器，对命中目标造成15点伤害，攻击间隔0.5秒。', minShopLevel = 1, page = '武器', price = 50, purchaseLimit = 0, implemented = true, source = '商店表!R26' },
        { number = 26, itemName = '指虎', itemKey = 'item134', description = '近战武器，对命中目标造成10点伤害，攻击间隔0.5秒。', minShopLevel = 1, page = '武器', price = 24, purchaseLimit = 0, implemented = true, source = '商店表!R27' },
        { number = 28, itemName = '背包升级6', description = '购买后，道具栏+1，背包格+10', minShopLevel = 6, page = '升级', price = 3200, purchaseLimit = 1, upgrade = { kind = 'backpack', level = 6, itemBarSlots = 8, backpackSlots = 40 }, implemented = true, source = '商店表!R29' },
        { number = 29, itemName = '背包升级5', description = '购买后，道具栏+1，背包格+5', minShopLevel = 5, page = '升级', price = 1600, purchaseLimit = 1, upgrade = { kind = 'backpack', level = 5, itemBarSlots = 7, backpackSlots = 30 }, implemented = true, source = '商店表!R30' },
        { number = 30, itemName = '背包升级4', description = '购买后，道具栏+1，背包格+5', minShopLevel = 4, page = '升级', price = 800, purchaseLimit = 1, upgrade = { kind = 'backpack', level = 4, itemBarSlots = 6, backpackSlots = 25 }, implemented = true, source = '商店表!R31' },
        { number = 31, itemName = '背包升级3', description = '购买后，道具栏+1，背包格+5', minShopLevel = 3, page = '升级', price = 400, purchaseLimit = 1, upgrade = { kind = 'backpack', level = 3, itemBarSlots = 5, backpackSlots = 20 }, implemented = true, source = '商店表!R32' },
        { number = 32, itemName = '背包升级2', description = '购买后，道具栏+1，背包格+5', minShopLevel = 2, page = '升级', price = 200, purchaseLimit = 1, upgrade = { kind = 'backpack', level = 2, itemBarSlots = 4, backpackSlots = 15 }, implemented = true, source = '商店表!R33' },
        { number = 33, itemName = '背包升级1', description = '购买后，道具栏+1，背包格+5', minShopLevel = 1, page = '升级', price = 100, purchaseLimit = 1, upgrade = { kind = 'backpack', level = 1, itemBarSlots = 3, backpackSlots = 10 }, implemented = true, source = '商店表!R34' },
        { number = 34, itemName = '远程武器升级5', description = '远程武器伤害提升10%', minShopLevel = 7, page = '升级', price = 8000, purchaseLimit = 1, upgrade = { kind = 'ranged', level = 5, increment = 0.1 }, implemented = true, source = '商店表!R35' },
        { number = 35, itemName = '远程武器升级4', description = '远程武器伤害提升10%', minShopLevel = 6, page = '升级', price = 4000, purchaseLimit = 1, upgrade = { kind = 'ranged', level = 4, increment = 0.1 }, implemented = true, source = '商店表!R36' },
        { number = 36, itemName = '远程武器升级3', description = '远程武器伤害提升10%', minShopLevel = 5, page = '升级', price = 2000, purchaseLimit = 1, upgrade = { kind = 'ranged', level = 3, increment = 0.1 }, implemented = true, source = '商店表!R37' },
        { number = 37, itemName = '远程武器升级2', description = '远程武器伤害提升10%', minShopLevel = 4, page = '升级', price = 1000, purchaseLimit = 1, upgrade = { kind = 'ranged', level = 2, increment = 0.1 }, implemented = true, source = '商店表!R38' },
        { number = 38, itemName = '远程武器升级1', description = '远程武器伤害提升10%', minShopLevel = 3, page = '升级', price = 500, purchaseLimit = 1, upgrade = { kind = 'ranged', level = 1, increment = 0.1 }, implemented = true, source = '商店表!R39' },
        { number = 39, itemName = '弹容量升级3', description = '远程武器弹容提升50%', minShopLevel = 6, page = '升级', price = 3200, purchaseLimit = 1, upgrade = { kind = 'magazine', level = 3, increment = 0.5, roundUp = true }, implemented = true, source = '商店表!R40' },
        { number = 40, itemName = '弹容量升级2', description = '远程武器弹容提升50%', minShopLevel = 4, page = '升级', price = 800, purchaseLimit = 1, upgrade = { kind = 'magazine', level = 2, increment = 0.5, roundUp = true }, implemented = true, source = '商店表!R41' },
        { number = 41, itemName = '弹容量升级1', description = '远程武器弹容提升50%', minShopLevel = 2, page = '升级', price = 200, purchaseLimit = 1, upgrade = { kind = 'magazine', level = 1, increment = 0.5, roundUp = true }, implemented = true, source = '商店表!R42' },
        { number = 42, itemName = '爆炸物升级3', description = '爆炸物伤害提升20%', minShopLevel = 7, page = '升级', price = 6400, purchaseLimit = 1, upgrade = { kind = 'explosive', level = 3, increment = 0.2 }, implemented = true, source = '商店表!R43' },
        { number = 43, itemName = '爆炸物升级2', description = '爆炸物伤害提升20%', minShopLevel = 5, page = '升级', price = 1600, purchaseLimit = 1, upgrade = { kind = 'explosive', level = 2, increment = 0.2 }, implemented = true, source = '商店表!R44' },
        { number = 44, itemName = '爆炸物升级1', description = '爆炸物伤害提升20%', minShopLevel = 3, page = '升级', price = 400, purchaseLimit = 1, upgrade = { kind = 'explosive', level = 1, increment = 0.2 }, implemented = true, source = '商店表!R45' },
        { number = 45, itemName = '近战武器升级7', description = '近战武器伤害提升10%', minShopLevel = 7, page = '升级', price = 3200, purchaseLimit = 1, upgrade = { kind = 'melee', level = 7, increment = 0.1 }, implemented = true, source = '商店表!R46' },
        { number = 46, itemName = '近战武器升级6', description = '近战武器伤害提升10%', minShopLevel = 6, page = '升级', price = 1600, purchaseLimit = 1, upgrade = { kind = 'melee', level = 6, increment = 0.1 }, implemented = true, source = '商店表!R47' },
        { number = 47, itemName = '近战武器升级5', description = '近战武器伤害提升10%', minShopLevel = 5, page = '升级', price = 800, purchaseLimit = 1, upgrade = { kind = 'melee', level = 5, increment = 0.1 }, implemented = true, source = '商店表!R48' },
        { number = 48, itemName = '近战武器升级4', description = '近战武器伤害提升10%', minShopLevel = 4, page = '升级', price = 400, purchaseLimit = 1, upgrade = { kind = 'melee', level = 4, increment = 0.1 }, implemented = true, source = '商店表!R49' },
        { number = 49, itemName = '近战武器升级3', description = '近战武器伤害提升10%', minShopLevel = 3, page = '升级', price = 200, purchaseLimit = 1, upgrade = { kind = 'melee', level = 3, increment = 0.1 }, implemented = true, source = '商店表!R50' },
        { number = 50, itemName = '近战武器升级2', description = '近战武器伤害提升10%', minShopLevel = 2, page = '升级', price = 100, purchaseLimit = 1, upgrade = { kind = 'melee', level = 2, increment = 0.1 }, implemented = true, source = '商店表!R51' },
        { number = 51, itemName = '近战武器升级1', description = '近战武器伤害提升10%', minShopLevel = 1, page = '升级', price = 50, purchaseLimit = 1, upgrade = { kind = 'melee', level = 1, increment = 0.1 }, implemented = true, source = '商店表!R52' },
    },
    Excluded = {
        { number = 27, itemName = '背包升级7', reason = '已确认仅六级升级；道具栏上限 8 格', source = '商店表!R28' },
    },
}
